### ISSUE TITLE
Find replacement gem for backbone-on-rails

### ISSUE THREAD

**Issue by mxie** [railsbridge/bridge_troll#1270]
The original gem [was yanked](https://rubygems.org/search?query=backbone-on-rails&yanked=true) and [the source code is also no longer maintained](https://github.com/meleyal/backbone-on-rails). We'll need to find a replacement or some other workaround. As is, `bundle install` will not succeed.

**Comment by ultrasaurus** [comment]
started looking at this with @desi -- see WIP PR https://github.com/railsbridge/bridge_troll/pull/1277

**Comment by ultrasaurus** [comment]
I *think* this is fixed by https://github.com/railsbridge/bridge_troll/pull/1278

**Comment by ultrasaurus** [comment]
seems to work!
