### ISSUE TITLE
when someone signs up to volunteer, show class preference after they choose to teach or TA

### ISSUE THREAD

**Issue by ultrasaurus** [railsbridge/bridge_troll#232]
A small improvement where the "Do you have a class level preference?" and "What's your experience with teaching?" is only shown after someone checks "Teaching" or "TAing"

on a page like this:  http://localhost:3000/events/2/rsvps/new/volunteer

the form is a bit overwhelming and whatever we can do to simplify it would be great:

"What's your experience teaching?" is above "Volunteer Preferences"

![screen shot with "Volunteer Preferences"  followed by two checkboxes:  "Teaching" or "TAing" then a large block of radio buttons with lots of text that might feel a little overwhelming to a new person](https://www.evernote.com/shard/s6/sh/dbcbdbb5-381c-4ce8-a938-53390a3d024a/f22e90219bf9269505f7576b7bf097fd/res/bdd9e01e-9fec-4989-ba87-9ce8ab301bdc/skitch.png?resizeSmall&width=832)

Instead I think it could be something like this:
![proposed UI screen shot described below](https://www.evernote.com/shard/s6/sh/ad4257ee-1388-4214-8327-ee56822766ac/e46514495233046b12d1b230b325a304/res/f1241abc-8321-4be7-be60-82b596413b52/skitch.png?resizeSmall&width=832)

Proposed UI simply re-arranges what is already there:
* Introduction
** What's your experience with this workshop's subject matter? (text area)
* Volunteer Preferences
** checkboxes: "Teach" or "TA"  (minor nit: TAing is a little awkward)
** hidden elements appear after one of the above check boxes is checked
* About You
** everything that is there now

This could be a nice starter for someone who knows javascript or good for anyone who enjoys front end / user experience improvement.

**Comment by siruguri** [comment]
@SarahPitts - are you still working on this? I just started digging into the codebase and can help you work through the seeds setup or anything else you'd like.

**Comment by lilliealbert** [comment]
@SarahPitts — is this still in progress? It's okay if not — I would just like to get a handle on whether or not this story should still be open.

**Comment by SarahPitts** [comment]
Sorry Lillie, I have had zero time lately to work on anything lately. It
would probably be best to take me off of it.

**Comment by tjgrathwell** [comment]
Should be satisfied by #330
