### ISSUE TITLE
Add ability to limit the number of volunteers for an event

### ISSUE THREAD

**Issue by glenna** [railsbridge/bridge_troll#283]
Or at least turn off Volunteer signups somewhere. Our event is two days away and someone just signed up to Volunteer.

From what I could find, there is only a way to limit the number of Students.

**Comment by kmolo** [comment]
I see that this issue started its life as two issues (limit number of volunteers, place an RSVP cutoff time), but then was modified to only be the first issue.

Seems to have been implemented by https://github.com/railsbridge/bridge_troll/pull/315

Possibly close this issue?

**Comment by kmolo** [comment]
Additionally, curious if Organizers count towards the Volunteer RSVP limit...I know Organizers are not included in the Volunteer count on the Check-In page, but haven't dug down into the code https://github.com/railsbridge/bridge_troll/commit/22c729a0e4fe2611cf9a31d8beecfe4abfbcd98d to see how that's handled here.

Do Organizers count towards the Volunteer RSVP limit?

**Comment by tjgrathwell** [comment]
Organizers are not counted against the Student or Voluntter RSVP limit. There can be infinity organizers.

Closing this issue as suggested, the additional feature for organizers to be able to shut down RSVPs will be done later.
