### ISSUE TITLE
Allow organizers to create event drafts

### ISSUE THREAD

**Issue by mxie** [railsbridge/bridge_troll#291]
I'm considering trying out BridgeTroll for the Boston chapter and was about to set up an event. After filling out what I can, I realize that I may not actually want to publish the event yet (though it also sounds like it goes through an approval process also?). Instead I'd like to preview or save it as a draft for now so that I can revisit later, perhaps with more details.

Thoughts on this feature? Has it been considered before?

**Comment by tjgrathwell** [comment]
The draft idea was completed in #334 and has been live for a while. Closing!

**Comment by mxie** [comment]
Awesome news!
