### ISSUE TITLE
students shouldn't be able to register for teacher training Session within Event

### ISSUE THREAD

**Issue by kmolo** [railsbridge/bridge_troll#293]
Currently, when students go to register for our latest event:

https://www.bridgetroll.org/events/132/rsvps/new/learn

...session that I chose to be 'Required for Students?' are checked & grayed out (i.e. can't be unselected).  However, the 'Teacher Training' session -- for which I unchecked the 'Required for Students?' checkbox -- is by default checked for the student to register for.  They can uncheck the box, but ideally the box would be unchecked & grayed out (i.e. unable to be selected by students, only available to volunteers).

In the meantime, setting the default value of the checkbox to unchecked for registrations that are (1) for students and (2) not 'Required for Students' would be an improvement in this case -- where students are indicating that they didn't mean to register for the teacher training session -- but I can see that for non-mandatory installfests, where students are meant to have a choice, a default opt-in setting wouldn't be best.

I recognize that Teacher Training could be established as a separate event instead of a session within the larger event, but it's convenient to have it included within the event as a session (events edits only have to be made in one event, not two separate events).

Looking from the front end (not having dug into the code yet), one way to implement this might be to create a per-Session 'Session Type' like the per-Event 'Event Type'  -- an either or choice between 'Students and Volunteers' or 'Just Volunteers' -- that way:
- 'Just Volunteer' sessions (like a teacher training) could be available only under Volunteer registration, and unchecked/grayed-out under Student registration, while
- 'Students and Volunteers' sessions that are not 'Required for Students' (like non-mandatory installfests) would be by default checked, but changeable.

**Comment by tjgrathwell** [comment]
This should be fixed as of 00a361c08c945a24291e1f8494bd09d5079fdb98
