### ISSUE TITLE
make RSVP questions customizable by course

### ISSUE THREAD

**Issue by kmolo** [railsbridge/bridge_troll#294]
[This issue is related to *Bridges other than Railsbridge using Bridge Troll.]

1) Currently student registration includes the following list of acceptable Operating Systems:

```
Mac OS X - Yosemite (10.10)
Mac OS X - Mavericks (10.9)
Mac OS X - Mountain Lion (10.8)
Mac OS X - Lion (10.7)
Mac OS X - Snow Leopard (10.6)
Mac OS X - Leopard (10.5)
Windows 8
Windows 7
Windows - Other
Linux - Ubuntu
Linux - Other
```

...but for the 'Intro to iOS' workshop, only these two are acceptable:

```
Mac OS X - Yosemite (10.10)
Mac OS X - Mavericks (10.9)
```

2)  Additionally, we'd like to add a radio selector asking which of the following versions of the XCode IDE that they have installed:

```
XCode 6.2
XCode 6.1.1
XCode 6.1
XCode 6.0.1
```

3) And maybe a free form question that lets them list which programming languages they use & which design software (Photoshop, etc).

4) And we'd like to ask these questions as volunteers register too.

These questions will allow us to better group the students & the instructor/TAs.

Only Question no.1 is really a need as we have to contact students to let them know that, while offered, the other operating systems won't work for this workshop.

**Comment by kmolo** [comment]
Just want to say that MobileBridge especially interested in (1) for our iOS development workshop since we have to email students who register with Linux, Windows or older OS X operating systems to ask them if they have access to either OS X 10.9 or 10.10, and, if not, to consider our Android workshop instead.

**Comment by tjgrathwell** [comment]
I took a shot (716885053c80beffa709c43efc0bd1437559d4c7) at adding some code to solve that first issue. Events now have a list of `allowed_operating_system_ids` which an organizer can configure like this:

![screen shot 2015-05-11 at 12 55 06 pm](https://cloud.githubusercontent.com/assets/1041691/7573752/e0b91630-f7dc-11e4-99fe-a2749ec4726e.png)

...and if only a subset of the OSes are allowed, the student RSVP form looks like this:

![screen shot 2015-05-11 at 12 57 19 pm](https://cloud.githubusercontent.com/assets/1041691/7573759/ef94a002-f7dc-11e4-8033-136d613fd328.png)

This implementation is probably **too** generic (you'd have to be a real monster to set up an event as "all OSes but Windows 7"), and involves a bit too much clicking. There might also be a need for some text explaining to students why only certain OSes are allowed.

What do you think?

**Comment by kmolo** [comment]
That looks great for our purposes!

\> This implementation is probably too generic (you'd have to be a real monster to set up an event as "all OSes but Windows 7"), and involves a bit too much clicking

You could create a 'Select All' -- all the checkboxes start un-checked unless you 'Select All' -- and then you just un-check the ones you don't want.

Not sure if that would be easy or difficult to implement.

**Comment by lilliealbert** [comment]
It seems like the main pain point here was addressed, so I'm going to close this issue for now. If there are further feature requests on this line, please open new issues! Thanks.
