### ISSUE TITLE
if 'send announcement email automatically' flag is unchecked, there is no way for organizers to send one later

### ISSUE THREAD

**Issue by kmolo** [railsbridge/bridge_troll#295]
In order for my co-organizers to look at the event I created before it was emailed out to everyone being notified about new San Francisco events (a separate need that is being resolved by Issue #291 'Allow organizers to create Event drafts'), I un-checked the 'send announcement email automatically' flag -- and currently there is no way for an Organizer to send the announcement email out later. @lilliealbert with her higher admin privileges had to send one out for us.

It seems that this could be resolved by either giving Organizers the ability to initiate an announcement email later, or (once Draft status is available) creating an alert that warns Organizers that this is their one opportunity to send one.

**Comment by lilliealbert** [comment]
Hey @kmolo, this got done last summer! Sorry for the delay in letting you know >_<

**Comment by lilliealbert** [comment]
(In that, now, if you don't want to send the announcement email upon approval, you can click a button to send it later, after it's been approved.)

**Comment by kmolo** [comment]
Yay!
