### ISSUE TITLE
Manage Chapter has links to destroy unaffiliated chapters when signed in

### ISSUE THREAD

**Issue by technicalpickles** [railsbridge/bridge_troll#307]
I was clicking around trying to find out if I can subscribe to a chapter's new events, and came across 'Manage Chapters' on the homepage. I was surprised to see Destroy links for a few of them on https://www.bridgetroll.org/chapters

![](http://cl.ly/image/1X050A223Z3a/Image%202015-03-04%20at%2010.30.41%20AM.png)

Looking a little more closely, it seems to only be chapters that have 0 locations and 0 events.

**Comment by tjgrathwell** [comment]
This is on purpose, anyone can delete a chapter that isn't being used.

Anyone can create a chapter, so the ability to delete them as a non-admin is needed for symmetry.

**Comment by tjgrathwell** [comment]
@technicalpickles is that a satisfying enough explanation, or do you think that something should be changed here?

**Comment by technicalpickles** [comment]
@tjgrathwell that makes sense, thanks!

The parity makes sense, but I would suggest an alternative. Maybe anyone can create a chapter, and if you create a chapter, you can delete it, in addition to admins being able to delete it.

It looks like a Chapter `has_many :leadership`. I'm not sure if you create it, if you are added to leadership, and if you can delete a chapter as leadership.

**Comment by tjgrathwell** [comment]
That's definitely doable.

The concept of chapter leadership didn't exist when the original deletion model was put in place. Currently when you create a chapter you do become its leader, so it could function the way you describe.

**Comment by lilliealbert** [comment]
I'm going to close this issue, since it doesn't seem like a very high priority change. If someone wants to lock down chapter deletion to a small group, I think that would be fine, but there are lots of other potential features that would be higher value to Bridge Troll users.
