### ISSUE TITLE
Display per-session dietary restrictions

### ISSUE THREAD

**Issue by kmolo** [railsbridge/bridge_troll#316]
Break down the dietary restrictions page on a per-session basis, showing the same data, just per-session.

---
Original issue:

We plan to offer food at our Teacher Training & InstallFest sessions:

https://www.bridgetroll.org/events/159

...but can only see the aggregate number of Vegetarians, Vegans, Gluten-Free, Dairy-Free folks, so we're unable to tell how many of these will be attending the Teacher Training or the InstallFest.

I can imagine quite a number of ways for this to be displayed:
- have these numbers as matrix per session in the 'Dietary Needs' section
- have these restrictions associated with the individual in the 'Show all Attendee RSVP Details' section

...those just being the two ways that occur to me immediately, but you know the complexity of these options better than me, so we're happy as long as we can find this information somewhere.

**Comment by lilliealbert** [comment]
@kmolo Sounds good! I changed the title to reflect the first option you mentioned. 

It looks like you've found a bug, though — I would have expected ALL restrictions to show up on the RSVP details page, and it looks like only the custom ones are. I'll put in a separate bug for that.

**Comment by kmolo** [comment]
Some more detail:

> This weekend we were correcting a snafu (no vegan or gluten-free lunch items ordered) and also had only 38% of our attendees show up to our workshop this weekend, so to make sure the vegan & gluten-free meals were even necessary to order and to confirm that our planned order would meet their needs, we had to go to each classroom and ask if anyone was vegan or gluten-free (which kinda put them on the spot).

Instead it would be nice if one could see (or click on and then see) which attendees require each dietary requirement.

Thanks for considering this within this larger feature request.

**Comment by lilliealbert** [comment]
@kmolo That information is actually available on the participant details page — there was a bug where only the custom text box dietary requirements were showing up, not all of them. You can see what that looks like: https://www.bridgetroll.org/events/159/attendees

Perhaps it'd be worth mentioning that individual dietary requests are listed on that participant details page on the aggregate dietary requests page itself in case people don't see it.

**Comment by kmolo** [comment]
Voila! Bug fix #322  to the rescue.

You might leave this issue (#316) open as a low priority issue.  It would be nice to have the numbers of particular dietary restrictions in a matrix table ('dietary needs' categories by session).

However, our teacher trainings are small enough that we can manually go thru the 'Show All Attendee RSVP Details' for this information, so a very very low priority issue.

**Comment by kmolo** [comment]
After latest workshop, I thought it might be nice to have dietary requirements of only those who are checked in to the workshop.  Can do this manually, by already having a list of the special dietary considerations & individually checking on whether these folks registered.

But I thought I would add this comment as something for the implementer(s) to think about.

**Comment by dannyshafer** [comment]
A friend and I took care of this at a RB event yesterday. It's in pull request #435. :D

**Comment by kmolo** [comment]
Awesome @dannyshafer -- thanks!

**Comment by lilliealbert** [comment]
@kmolo Can you tell me a little bit more about how you would use the checked-in counts for dietary restrictions?

I want to make sure that we present this information in such a way that it's useful to organizers when it's most relevant / needed.
