### ISSUE TITLE
'Student RSVP Details' in 'Organizer Console' does not show all student details

### ISSUE THREAD

**Issue by possibly** [railsbridge/bridge_troll#317]
Organizer Console -> Tools for before the event -> 'Show all Attendee RSVP details' section. Not all recorded details that are asked in the RSVP form are shown. 

For example, the class level question (blue, green or gold) is asked and even recorded if you click the "download student details csv" and check the csv file. In fact, only dietary info, details, gender, pre-event contact, operating system and waitlisted details are shown on the web, while the csv file additionally collects class level, dietary info and potential projects.

RSVP form:
![rsvpform](https://cloud.githubusercontent.com/assets/1417341/7017605/aee371e4-dcae-11e4-9045-95531aa93faa.png)

Student details in the 'Show all Attendee RSVP details' section.
![screen shot 2015-04-06 at 10 47 38 pm](https://cloud.githubusercontent.com/assets/1417341/7017606/b3a8c648-dcae-11e4-8033-e3534dadace8.png)

print out of the sections contaiend in the student details .csv file.
![screen shot 2015-04-06 at 10 47 21 pm](https://cloud.githubusercontent.com/assets/1417341/7017612/c24828f6-dcae-11e4-9203-e2ee12991489.png)

**Comment by lilliealbert** [comment]
Hi @possibly. You're looking at a fork of the Bridge Troll app by OpenHatch, and I believe they've made some changes to the RSVP form, and it sounds like they haven't made the corresponding changes to the Student RSVP details.

There is a class organizer in Bridge Troll that we encourage organizers to use to break into small groups;  we also show aggregate dietary needs on a separate page on Bridge Troll.

Could you specify which specific information you think should be added to the CSV? If it's specifically the project information, that doesn't exist in this project, only in OpenHatch's fork.

**Comment by possibly** [comment]
Doh! Your totally correct, I was going fast and did not realize I am not in OpenHatch's fork. Closing this and moving it to OpenHatch's fork.

**Comment by shaunagm** [comment]
@possibly - the bridgetroll repo is under my account, not openhatch's, FYI.  (Should probably change that.)  You can add the issue here: https://github.com/shaunagm/bridge_troll/issues
