### ISSUE TITLE
GitHub user name exposing my email address

### ISSUE THREAD

**Issue by JenniferMack** [railsbridge/bridge_troll#318]
For some reason the email address that I signed up with became set as my GitHub user name. It also refuses to be changed. I’ve tried the user name by itself, the full URL, and garbage characters. It saves, and then when I go back to the page, the email address is back in the GH user name field.

Normally, I wouldn’t even mention this, but it’s showing my email address on the profile page in clear text. Sort of annoying.

**Comment by tjgrathwell** [comment]
Hey @JenniferMack, I'm not sure I follow.

When I visit https://www.bridgetroll.org/users/5021/profile I see the GitHub username is set to https://github.com/JenniferMack (though it should be set to just `JenniferMack`). I don't see any email addresses here, is this the wrong page for me to be looking at?

**Comment by JenniferMack** [comment]
It’s different now. Guess it was a glitch.
