### ISSUE TITLE
Organizers should be able to tell who received which email

### ISSUE THREAD

**Issue by pwnela** [railsbridge/bridge_troll#319]
We're less than a week away from our workshop, and we sent an email with important details to all students a couple of days ago. A few more students have signed up (and a few have un-RSVPed) and I'm not seeing a way to tell who the new students are in order to send them the same email.

I'd like to avoid emailing everyone the same email, so having some way to see un-emailed students, or new students since a certain day, would be super helpful!

(Once the workshop and RailsConf is over, I'd love to help implement this, but wanted to get the conversation going in case I was missing some tool/feature that would already solve this issue.)

**Comment by tjgrathwell** [comment]
What kind of content is in these emails? Is it sensitive in some way, e.g. has details that you don't want to be publicly available?

My preferred way to handle this situation is for the organizer to update the "student details" or "volunteer details" on the event itself. Any student who RSVPs for the event will receive an email with the most current student_details/volunteer_details (depending on their role). If they get promoted from the waitlist, they'll receive the details again at that time.

This means the organizer doesn't have to keep checking for new RSVPs just to send them the same information.

These details DO get sent to RSVPing attendees even if they're starting on the waitlist, which you may or may not want. If that's an issue, we can change it so the details only go to attendees as they get confirmed.

Alternatively, we could include the RSVP create date in some of the CSV / table dumps, which you could use for whatever purpose. But I'd prefer the experience where the "average organizer" needs to do as little work as possible.

**Comment by lilliealbert** [comment]
I think @tjgrathwell's suggestion for updating the event is pretty sane. I'm going to close this for now, but feel free to open another issue if this is an ongoing problem. Thanks!
