### ISSUE TITLE
Automatically send post-workshop survey after the event

### ISSUE THREAD

**Issue by lilliealbert** [railsbridge/bridge_troll#326]
Currently organizers have to click the "Send Survey" button after the workshop to send one. It'd be nice if we send it automatically.

We probably don't want to send surveys for volunteer meetups, so only send surveys for workshops where allow_student_rsvp is true.

**Comment by ultrasaurus** [comment]
Love this idea!  There's also the case where some groups are using meetup or eventBrite to do signups, so we might want to distinguish that case.

**Comment by lilliealbert** [comment]
@tjgrathwell did it: 71d11ed93f537ccbca6abe99c474ee529e83465e

:rocket: :rocket: :rocket:
