### ISSUE TITLE
Ask students if they were in the right class

### ISSUE THREAD

**Issue by lilliealbert** [railsbridge/bridge_troll#329]
Only show this survey question to students!

Question: Was the class or section you were in appropriate to your skill level? 

helper text: Please let us know if you switched sections or classes (or wish you had), and whether your original section/class was too fast, too slow, or something else.

**Comment by ultrasaurus** [comment]
I've always valued making people feel comfortable with switching and emphasizing that they are in control of their own learning.  I wonder what we would do with the info from the survey?  Mostly workshops are organized by different people and the final sorting is mostly a human process.

**Comment by baw** [comment]
I can work on this.

**Comment by lisahamm** [comment]
I have opened a [PR](https://github.com/railsbridge/bridge_troll/pull/555) to address this issue.

**Comment by tjgrathwell** [comment]
Closed by #555
