### ISSUE TITLE
duplicate location in BridgeTroll.org -- could they be merged?

### ISSUE THREAD

**Issue by kmolo** [railsbridge/bridge_troll#331]
Hi,

There are 2 duplicate entries for 'Pivotal Labs (Railsbridge San Francisco)'

https://www.bridgetroll.org/locations/5
https://www.bridgetroll.org/locations/14

...low priority, but can these locations be merged into one?

Additional possible/separate issue that might be opened:

> create location 'Archive' button in addition to 'Edit' and 'Destroy' 
- this would be used when a company moves form their old address:
  - the location would no longer be displayed on [https://www.bridgetroll.org/locations](https://www.bridgetroll.org/locations)
  - but the location would still be viewable on the event pages of past events that were held there
  - [https://www.bridgetroll.org/locations](https://www.bridgetroll.org/locations) page could include an 'Archive' button which would lead to a listing of archived locations, from which archived locations could be brought back
- I haven't tested what 'Destroy' does, but I wonder what happens to the location information on event pages of past events which took place at the old address which has now been 'Destroyed' in the database -- do they show no location, or is the old location frozen in some way
- as a sample, there is a '[Pivotal Labs HQ (Railsbridge San Francisco)](https://www.bridgetroll.org/locations/2)' location at 731 Market -- I wonder if this is still a current/valid address, or has Pivotal moved from this address to the 875 Howard St address.

**Comment by tjgrathwell** [comment]
Okay, I've consolidated the two locations' events under the older one (id=5).

The other Pivotal is indeed the old market street address, and it would be nice to be able to flag it as "archived" as you describe. I've made that a new issue as #332 in case anyone wants to give it a go.

The "Destroy" button right now only shows up for locations with zero events, so destroying a location never removes information from an event.

If a location was to be destroyed anyway, despite that restriction, the event pages that formerly used it would just show as having "No location".

Thanks for bringing this up!

**Comment by kmolo** [comment]
> The "Destroy" button right now only shows up for locations with zero events, so destroying a location never removes information from an event.
> If a location was to be destroyed anyway, despite that restriction, the event pages that formerly used it would just show as having "No location".

Good to hear!
