### ISSUE TITLE
Old locations should be flagged as no longer usable

### ISSUE THREAD

**Issue by tjgrathwell** [railsbridge/bridge_troll#332]
Spun out from #331

If a venue moves or goes out of business, its location should no longer be usable for new events.

Certain users should be able to 'archive' a location to ensure it no longer shows up in the available locations dropdown. The appearance of the location on old event pages should not change, except maybe to show a "closed" or "archived" label. The button to archive an location should be on the Location edit page.

The users allowed to archive a location should probably be the same as those allowed to edit one [(see Location#editable_by?)](https://github.com/railsbridge/bridge_troll/blob/master/app/models/location.rb#L21):
* Admins
* Chapter leaders
* Someone who organized a published event at that location

Here's an example location for archiving once this feature works, Pivotal's old office on Market: https://www.bridgetroll.org/locations/2

**Comment by BrainScraps** [comment]
okay - so I'm looking at different components of this issue and getting ready to work on it. Feedback would be appreciated, @tjgrathwell 


- [ ] Create migration that adds a `archived_at` column to the `locations` table
- [ ] create `archive!` and `archived?` methods in `location.rb`
- [ ] Add `archivable_by?` that uses `editable_by?` and `additional_details_editable_by?` logic
- [ ] Add "Archive" button to the right of the "Update Location" button on `locations/edit` (only for the right users) (should that be red, or yellow?)
- [ ] Remove "Edit" button in the `locations/index` for archived locations
- [ ] Change `collection_select` to use only non-archived locations

**Comment by tjgrathwell** [comment]
@BrainScraps That all looks good!

Orange or red sounds good for the archive button to differentiate it from `Destroy`.

**Comment by tjgrathwell** [comment]
This is fixed by #333 and I've marked the old Pivotal office as Archived.

**Comment by kmolo** [comment]
When looking at the Archived old Pivotal office:

https://www.bridgetroll.org/locations/2

...as an unprivileged user, there is no marking that indicates that this location is archive, other than indirectly inferring this because there is no 'Edit' button.

Would be nice if such locations could be labeled 'Archived' in some way that the unprivileged user could see.  [Super super low priority]

**Comment by tjgrathwell** [comment]
That's fair. I'll file it as another issue.
