### ISSUE TITLE
Script/bootstrap is specifying Ruby 2.1.2

### ISSUE THREAD

**Issue by mejarc** [railsbridge/bridge_troll#336]
In the course of installing bridge_troll on localhost, I ran `script/bootstrap`.

The script spit out an error based on lines 91-94:

````
	if ! is_ruby_version "ruby 2.1.2"
	then
		alert_wrong_ruby_version "2.1.2"
	fi
````
The Gemfile specifies Ruby 2.2.2, so script/bootstrap requires updating to stay in sync.

**Comment by tjgrathwell** [comment]
Whoops, that's an oversight.

Would you mind making a pull request to fix it?

**Comment by mejarc** [comment]
I'll set to work on that!
