### ISSUE TITLE
after signing up (difficult process), I’m still “not logged in” when I hit volunteer

### ISSUE THREAD

**Issue by ultrasaurus** [railsbridge/bridge_troll#340]
https://twitter.com/agius/status/619189085454729216
![image](https://cloud.githubusercontent.com/assets/41906/8619381/86225786-26cb-11e5-83de-3ba75a8ae451.png)

**Comment by ultrasaurus** [comment]
@agius how did you try to sign up?  twitter? github? email and password?  what part was difficult?

**Comment by tjgrathwell** [comment]
While I appreciate the spirit of helpfulness and improvement inherent in this issue, I don't think issues should be filed on behalf of other humans who may never follow up on it.

I'm going to close this for now, but if there's any actionable things to follow up on please reopen.
