### ISSUE TITLE
Gravatar button not working

### ISSUE THREAD

**Issue by mdcramer** [railsbridge/bridge_troll#346]
When I click on the "change gravatar" button a WP login page opens in a new tab. When I log into that page the WP tab disappears and the BridgeToll page then switches to the same WP login page. Clicking "sign in with WP" just caused the page to reload. I've duplicated this in Firefox and Chrome.

**Comment by siruguri** [comment]
I wonder if this is a Gravatar/WP problem? If you have a Gravatar.com window open already, this doesn't happen ... at any rate, after you change your Gravatar, and re-open your /users/edit page on bridgetroll, you shd see the Gravatar change (after their cache has reloaded.) Do you see that happen?

**Comment by mdcramer** [comment]
This is pretty terrible. If I open Gravatar.com in another window I'm able to log in no problem. When I click "change gravatar" I switch to the Gravatar.com window and am on the "Manage Gravatars" page. Mousing over the "change gravatar" button shows that it's pointing to https://en.gravatar.com/emails, so this is not a surprise. What is surprising, however, is that I can't change the gravatar. Repeatedly clicking the button just keep opening new tabs.

OK, it's a browser caching issue. If I shift-reload the page the gravatar is updated. Ugh.

**Comment by lilliealbert** [comment]
Caching is hard!
