### ISSUE TITLE
Assigning potential leaders for chapter not functioning

### ISSUE THREAD

**Issue by rjulian** [railsbridge/bridge_troll#347]
Search doesn't seem to be going through users when looking to assign a potential leader for a chapter. Even inputting a valid username and hitting assign does nothing.

**Comment by tjgrathwell** [comment]
Is this the same as #369?

**Comment by tjgrathwell** [comment]
Hopefully fixed from #369.

**Comment by carlisia** [comment]
I'm digging through open and closed issues to learn about more features than I can figure out via the website. I'm interested in this one. Where do I assign ppl to be a chapter leader and/or potential chapter leader? Also,  are we able to have, say, a GoBridge chapter leader for SF, and a Rails chapter leader for SF?

**Comment by lilliealbert** [comment]
Chapter leaders are currently added by Bridge Troll admins. 

We need to change the data model so that there can be a separate GoBridge chapter and RailsBridge chapter in SF. This is something we're trying to figure out now — currently there is one "chapter" per city/region.
