### ISSUE TITLE
map shows incorrect location

### ISSUE THREAD

**Issue by ultrasaurus** [railsbridge/bridge_troll#354]
I'm pretty sure it was correct last week.  Took a snapshot to show what it looks like now.  For [this event](https://www.bridgetroll.org/events/181), it should show someplace close to 5th & Mission

![image](https://cloud.githubusercontent.com/assets/41906/9050202/fe0d0b50-39ff-11e5-97c7-9faa8fa66e63.png)

**Comment by lilliealbert** [comment]
The "(5th Floor Events Space)" was messing with Google maps, it seems. I moved that down to the 2nd address line on the location and that fixed it.
![screen shot 2015-08-03 at 5 46 53 pm](https://cloud.githubusercontent.com/assets/978428/9050846/a734cee6-3a07-11e5-8b11-21575f936f08.png)
