### ISSUE TITLE
Under 'Childcare Requests' possibly list those requests which are currently on Wait List

### ISSUE THREAD

**Issue by kmolo** [railsbridge/bridge_troll#355]
Would be convenient to have all childcare request information -- including those that are on the Wait List -- listed under the main 'Childcare Requests' section on the main Organizer Tools screen.

Presently, organizers have to navigate into 'Show all Attendee RSVP Details' and sort by 'Childcare Info'  to find all the childcare requests.

And at that point, the organizers still can't see where on the Wait List a potential student with a childcare request is -- the 'Show all Attendee RSVP Details' table only includes a yes/no column for 'Waitlisted' -- so then they need to return to the event page & search to find out if the childcare request is no.4 on the Wait List or no.44, and thus how likely they'll need to provide care for those children.

---

This is a low priority issue since there is a way to figure this out, but would be more convenient to have them all together (and organizers are less likely to have a previously-unnoticed childcare request pop off the waiting list in the last few days before a workshop).

**Comment by lilliealbert** [comment]
I think ultimately we need to limit childcare RSVPs to a week or so before the workshop happens; if someone is added to the waitlist with a kid to bring, we should be communicating with them that the organizers might not be able to have a playgroup ready. It's not fair to organizers to need to hustle to find someone to organize the playgroup on less than a week's notice.

**Comment by ultrasaurus** [comment]
This seems to be addressed in "Show all Attendee RSVP Details" where you can see childcare requests in the list of all RSVPs (waitlisted or not)

![image](https://user-images.githubusercontent.com/41906/55278431-5a654080-52c9-11e9-8efc-786587fe0246.png)
