### ISSUE TITLE
Count of Organizers missing several places where count of Volunteers & Students are found

### ISSUE THREAD

**Issue by kmolo** [railsbridge/bridge_troll#356]
Hello,

There seems to be a default assumption that all Organizers will & do attend every session of the workshop.

---

Organizers are partially included in the session check-ins:
- the Organizer who created the event & Bridgetroll members who were directly added as Organizers (without first registering as Volunteers):
  - are not listed on the check-in page
  - are not included in the total entry count (this total number can be useful for ordering food)
- Organizers who first RSVPed as Volunteers & then were elevated to Organizers:
  - ARE listed on the check-in page with a Role of Organizer in place of the original Role of Volunteer
  - ARE included in the total entry count

For example, see the Teacher Training session for BridgeTroll Event [#177](https://www.bridgetroll.org/events/177):
- there are 4 Organizers total, only 2 of which first RSVPed as Volunteers
- there are 12 Volunteers RSVPed to the Teacher Training
- on the **checkin** page:
  - there are 14 entries (12 + 2), but 
  - the Volunteer check-in totals are **10 / 12** (10 Volunteers attended, 2 Volunteers didn't, 2 listed Organizers are counted in this total even though counted in 14 entries total, last 2 Organizers who were never registered as Volunteers aren't included on this check-in page)

Similar dynamic for other session check-ins (InstallFest, Workshop).

---

Under the 'Email Attendees' section, as documented in issue https://github.com/railsbridge/bridge_troll/issues/282, Organizers are not included in any emails -- not even Organizers who started out as Volunteers.

---

EDIT: Organizers cannot request childcare.  I know, they know whether or not they need childcare, so not necessary for event management.  Just another area in which Organizers are not reflected.

---

EDIT 2: Organizers dietary restrictions don't seem to be noted anywhere, even if they originally signed up as volunteers, before being promoted to organizer.

**Comment by kmolo** [comment]
For the purposes of getting the dietary restrictions for particular sessions like Teacher Training, would be nice to include Organizers in the 'Show All Attendee RSVP Details' section.

**Comment by lilliealbert** [comment]
@kmolo Were you a software tester in another life? You have a gift for it :D

Could you tell me a little more about what the specific pain point is with this? Is it mostly around food ordering, or are there other places where the app hasn't included organizers and it caused trouble?

**Comment by kmolo** [comment]
The real pain point is getting the dietary restrictions.  

However, the difficulty with displaying the dietary restrictions is first getting them -- there are 3 ways that one can become an Organizer:
  - create the event
  - add Organizers who have BridgeTroll accounts, but who have not RSVPed as volunteers
  - add Organizers who have BridgeTroll accounts, and who have RSVPed as volunteers

...currently the dietary restrictions are collected only for the third set of organizers (collected when they RSVP as volunteers).

p.s. Personally I'd like the other features too...ability to:
  - check-in organizers per session since they don't necessarily attended every session
  - CC organizers on emails sent from BridgeTroll
  - document childcare request from organizers

**Comment by kmolo** [comment]
However, I recognize that architecturally this might be difficult to build into BridgeTroll, and so the answer might just be "can't/won't, BridgeTroll users just have to manage this outside the app."

I would be fine with this answer, if it needs to be.

**Comment by lilliealbert** [comment]
I'm going to close this out since it's been a while. It seem like a non-technical solution (asking co-organizers for their dietary restrictions) is the way to go for now.
