### ISSUE TITLE
Volunteer remains in 'Section Organizer' even after un-RSVP-ing for session (multi-session workshop, so still attending other sessions)

### ISSUE THREAD

**Issue by kmolo** [railsbridge/bridge_troll#357]
Volunteer found in 'Unsorted Attendees - Volunteer' section:

https://www.bridgetroll.org/events/177/organize_sections

...changed her RSVP to indicate that she would not be coming to the workshop session (only the teacher training & installfest sessions), however she remains in the 'Section Organizer.'

When we navigate to the session check-in for the workshop, she is not there to be checked in.  Other students & volunteers will disappear form the 'Section Organizer' when they un-RSVP (though they were probably canceling their RSVPs instead of editing them).

Thoughts on why this remains?

---

I use the 'Section Organizer' prior to the workshop to break students & teachers/TAs out into rooms, and make sure we've recruited enough volunteers.  This might be outside of the 'Section Organizer' purpose, but it's super useful.

**Comment by lilliealbert** [comment]
The section organizer currently includes all the people who have RSVP'd to any session for the workshop, so since that person is still RSVP'd to a session, they are still going to show up.

We *could* change this, but it seems like it'd be complicated, so let's punt for now.
