### ISSUE TITLE
Show each event's sessions chronologically

### ISSUE THREAD

**Issue by rearadmiral** [railsbridge/bridge_troll#359]
Probably no one noticed before with Classic Events because Friday comes before Saturday alphabetically but now that people are adding Teacher Trainings and other sessions under an event, the sort order gets weird and confusing.

SF Mobilebridge: pilot Android Development Workshop
Friday, August 07, 2015: InstallFest
Saturday, August 01, 2015: Teacher Training
Saturday, August 08, 2015: Workshop

I can fix this but just wanted to make sure we didn't want the way it is now for some other reason.

**Comment by kmolo** [comment]
@rearadmiral there was no reason from the workshop organizer perspective

**Comment by tjgrathwell** [comment]
@rearadmiral To clarify, where is it showing up out of order? In the event RSVP emails? Other places?

I don't think it's intentionally sorting alphabetically, the code for the email just says `@rsvp.rsvp_sessions.each` which means they probably come over in some weird arbitrary database ordering. Strange it has taken this long to find that out!

**Comment by rearadmiral** [comment]
Good to know. I noticed it on the main homepage that lists upcoming events but it might be other places. I'll do a search and make sure we use the order we want everywhere.

**Comment by rearadmiral** [comment]
I did some investigation yesterday and the code looks correct.  ```event.event_sessions``` is sorted by ```end_at``` which is what we want.

I captured that sort order above from prod but now that event is past so it's not shown anymore. I reproduced it once locally but could not reliably do so. If I see this on the live site again, I'll reopen and maybe we can investigate further. My only guess is in the controller adds more scopes and the ```upcoming``` class method adds another ```order('events.starts_at')``` which maybe affects the event_sessions order is a weird way—but it shouldn't so...

**Comment by kmolo** [comment]
@rearadmiral You can see it in a few cards on the event page right now:

https://www.bridgetroll.org/events

...check out:
- Madison Railsbridge Outreach for Women Workshop (Thu 8/20 workshop, Wed 8/19 installfest)
- SF MobileBridge: iOS Development for Women (Fri 9/25 installfest, Sat 9/26 workshop, Sun 9/6 teacher training)
- RailsBridge Cleveland (Sat 9/12 RailsBridge, Fri 9/11 installfest)
- RailsBridge Sacramento: Intro to Web Development (Fri 10/23 installfest, Sat 10/24 workshop, Thu 10/22 volunteer mixer)

Looks like it's alphabetizing on the the cards by day name.
on the upcoming [SF MobileBridgeSF iOS Workshop](https://www.bridgetroll.org/events/182)

**Comment by kmolo** [comment]
Strangely, when I am *not* signed into BridgeTroll, the sort order is correct, but once I *am* signed in, then it appears that it is alphabetizing by day name.

**Comment by kmolo** [comment]
Even more inconsistent, after signing in Bridgetroll.org on both Chrome & Internet Explorer, the ordering appears inconsistent:
- sometimes correctly by dates
  - Madison Railsbridge Outreach for Women Workshop (Wed 8/19 installfest,Thu 8/20 workshop)

- sometimes incorrectly alphabetically by day
  - Chicago Ruby on Rails Workshop for Women (Fri 9/11 installfest, Sat 9/12 workshop, Thu 9/3 TA training)
  - Railsbridge Cleveland (Fri 9/11 installfest, Sat 9/12 railsbridge)
  - RailsBridge Sacramento: Intro to Web Development (Thu 10/22 volunteer mixer, Fri 10/23 installfest, Sat 10/24 workshop)
- sometimes incorrectly reverse alphabetically by day
  - SF Ruby on Rails Workshop for Women (Sat 8/22 RoR workshop, Fri 8/21 installfest)
  - SF MobileBridge: iOS Development for Women (Sun 9/6 teacher training, Sat 9/26 workshop, Fri 9/25 installfest)

---
And, again, when I log out, everything is sorted in the correct order.

---

![bridgetroll_20150818_1317](https://cloud.githubusercontent.com/assets/4886396/9341585/a3d64b76-45ab-11e5-9333-2286a0210154.jpg)

![bridgetroll_20150818_1318](https://cloud.githubusercontent.com/assets/4886396/9341591/a855698e-45ab-11e5-8985-11da77663366.jpg)

**Comment by rearadmiral** [comment]
Something that random would suggest that @tjgrathwell 's hypothesis is correct and it's an unordered query that is therefore getting the DB order.
