### ISSUE TITLE
customize Registration Confirmation Email by course

### ISSUE THREAD

**Issue by kmolo** [railsbridge/bridge_troll#365]
I signed up as a volunteer for the [next MobileBridge iOS development course](https://www.bridgetroll.org/events/182), and the registration confirmation email included:

Be sure to review the curriculum before the workshop. We have several curricula available at http://docs.railsbridge.org

...as more *Bridges start using BridgeTroll.org, the curriculum link(s) provided should be customizable by course.

---
This is part of a family of issues regarding customization by course:
 - RSVP questions: https://github.com/railsbridge/bridge_troll/issues/294
 - registration confirmation email: https://github.com/railsbridge/bridge_troll/issues/365  (this one)
 - follow up survey email https://github.com/railsbridge/bridge_troll/issues/328

**Comment by lilliealbert** [comment]
@kmolo That text is customizable on the event page:

![screen shot 2015-11-08 at 3 07 19 pm](https://cloud.githubusercontent.com/assets/978428/11023334/9d5a705a-862a-11e5-8b0b-d54ef4892e6a.png)

We might want to change the default text not to specify RailsBridge, but at the moment Bridge Troll is mostly used for events using curricula at docs.railsbridge.org, so this seems less pressing than other issues.

**Comment by kmolo** [comment]
You're right.  It is an editable field, so user error on this one.

Closing issue.
