### ISSUE TITLE
Don't show draft events on Unpublished Events index

### ISSUE THREAD

**Issue by lilliealbert** [railsbridge/bridge_troll#366]
It's really confusing

https://www.bridgetroll.org/events/unpublished_events

**Comment by lilliealbert** [comment]
:heart_eyes:

**Comment by lilliealbert** [comment]
Hm, I think this might have made a different bug — the JS pairing workshop now doesn't show up on the unpublished events page.

**Comment by lilliealbert** [comment]
(Because `draft_saved` was nil, not false) 

((I just updated it in the console so I could publish this one))

**Comment by tjgrathwell** [comment]
Glarg, I was afraid of something like that.
