### ISSUE TITLE
"Potential Organizers" select in Assign Organizer super clunky and slow (SF chapter)

### ISSUE THREAD

**Issue by gkop** [railsbridge/bridge_troll#369]
Probably because there are 5879 options and growing :stuck_out_tongue_winking_eye:

The feature is therefore completely unusable on my iPad Air and remarkably difficult to use on my powerful laptop.

The quick fix may be to set the `minimumInputLength` on the select2 to, say, 3 characters.

Long term we should probably ajax-ify the searching for potential organizers.

**Comment by tjgrathwell** [comment]
It is ajaxified now.

Not the fastest search in the world, it isn't really leveraging any indexes. Probably want to re-evaluate when we hit those first hundred thousand users.
