### ISSUE TITLE
Locations should be sortable on the locations index page

### ISSUE THREAD

**Issue by scottyschup** [railsbridge/bridge_troll#376]
It would be nice if locations could be sorted by city, name, and most recently used (or most recently modified, since using a location modifies the count?).

**Comment by lilliealbert** [comment]
We use DataTables elsewhere in the app for sorting, so this seems like it would be a relatively straightforward addition.

**Comment by ultrasaurus** [comment]
FYI: @LauraKirby is working on sorting by most recently used location
