### ISSUE TITLE
The "Download Attendee Names CSV" output should include organizers

### ISSUE THREAD

**Issue by scottyschup** [railsbridge/bridge_troll#377]
If the purpose is to generate a list for security desks, maybe the organizers should also be allowed into the event :)

**Comment by lilliealbert** [comment]
Yeah, I think this hasn't come up before because typically organizers arrive way ahead of students and teaching volunteers, and are often escorted by the company hosting. But it certainly seems like it could be helpful and not to hard to add :)

**Comment by akanshmurthy** [comment]
@scottyschup this sounds like fun- would I start on this by adding to the index controller action of the attendees controller to also get organizers or am I off?

**Comment by kmolo** [comment]
Issue #356 is another issues looking for Organizers to be included.  You might consider these when designing your solution for this issue.

**Comment by tjgrathwell** [comment]
Fixed in #407
