### ISSUE TITLE
Refactor course to be ActiveRecord, rather than ActiveHash

### ISSUE THREAD

**Issue by lilliealbert** [railsbridge/bridge_troll#381]
now that we have 4, soon to be 5, would be nice to actually add/edit courses and their descriptions in the app

@ultrasaurus started a refactor here: started refactor here: https://github.com/ultrasaurus/bridge_troll/tree/course-yaml

**Comment by ultrasaurus** [comment]
oops -- I didn't realize I had anything in progress and recently deleted and re-create my fork.  Sorry about that!

**Comment by jmkoni** [comment]
https://github.com/railsbridge/bridge_troll/pull/518
Not 100% there, but I think it's pretty close.

**Comment by jmkoni** [comment]
https://github.com/railsbridge/bridge_troll/pull/519

New PR

**Comment by tjgrathwell** [comment]
Closed by #519
