### ISSUE TITLE
Validate that attendee RSVPs must have at least one rsvp_session

### ISSUE THREAD

**Issue by lilliealbert** [railsbridge/bridge_troll#382]
It's okay for organizer RSVPs not to have one, but for students and volunteers they should've cancelled their session instead of unchecking all boxes.

Adding the validation is pretty simple, the problem is making it not invalidate the ~400+ extant records that have no rsvp_sessions. Options:
- Only make the validation apply if the event is `upcoming?`
- Delete any old rsvps that don't have associated sessions (they _probably_ didn't go...)
- For old rsvps without sessions, make an `rsvp_session` for every `event_session` (it's the default...)

Probably only the first option is good, but it leads to more mind-juggling about when data is or isn't valid.

[imported from Pivotal Tracker on 11/8/15, original story by @tjgrathwell]

**Comment by LauraKirby** [comment]
I will take a look at this.
