### ISSUE TITLE
Users should be able to set email preferences on a per-course basis

### ISSUE THREAD

**Issue by lilliealbert** [railsbridge/bridge_troll#385]
Currently, when a user is a member of a chapter, they will receive emails for all events in that chapter.

As we build out different subject area (iOS, HTML, Rails, etc) we want attendees to have more control over their email preferences without needing to inflate the number of chapters (RailsBridge SF, MobileBridge SF, etc).

Therefore:
- On a user's profile page, they should get an extra set of checkboxes for their course email preferences
- When an event is sent out, it should only mail people who have signed up to receive mails for that course.
- When a new course is added, everyone who is subscribed to any emails for a chapter should be opted-in to emails for that course. Since courses are currently a hardcoded enum, this might just be a migration that happens on every course add. Might want to add a tripwire test to ensure that happens?

[imported from Pivotal Tracker on 11/8/15, original story by @tjgrathwell]

**Comment by kmolo** [comment]
+1

**Comment by lilliealbert** [comment]
The way we use courses has gotten more complicated since this was written, so I'm closing this. Let's revisit as needed.
