### ISSUE TITLE
Organizer can add a new event location page from Create Event page

### ISSUE THREAD

**Issue by lilliealbert** [railsbridge/bridge_troll#387]
The organizer can add an event location from the Add Event page via a link next to the Location drop down. The link should say "Add Location" and should open the Add Location form in a lightbox. Upon save, the new location should appear in the select location drop down.

AJAX!

**Comment by StevenXL** [comment]
@lilliealbert I am working on this. Running into issues but I'm posting to the google group.

**Comment by StevenXL** [comment]
@lilliealbert - this was addressed in PR #421

**Comment by tjgrathwell** [comment]
Closing thanks to #421

**Comment by lilliealbert** [comment]
(BTW, thanks, @StevenXL!!!! :tada: :tada: :tada:)
