### ISSUE TITLE
Add Google auth

### ISSUE THREAD

**Issue by lilliealbert** [railsbridge/bridge_troll#391]
We've got basically all the other major services, why not add Google?

**Comment by StevenXL** [comment]
@lilliealbert I've addressed this issue, at least from what I understood that you wanted, with [pull request #415](https://github.com/railsbridge/bridge_troll/pull/415). 

If this is not what you had in mind, let me know.

**Comment by StevenXL** [comment]
@lilliealbert The feature is done - I will write the tests tomorrow and likely submit a pull request then. (Unfortunately, I spent a lot of time hunting down a bug; I had to lock down the version of `omniauth-oauth2` used in the project).

What is the process for exchanging API keys / secrets, or will on of the project maintainers simply create their own? 

Thanks!

**Comment by StevenXL** [comment]
@lilliealbert - [pull request](https://github.com/railsbridge/bridge_troll/pull/419) for this issue is up.

**Comment by tjgrathwell** [comment]
Finished by #419
