### ISSUE TITLE
Section arranger student detail should include class level description

### ISSUE THREAD

**Issue by lilliealbert** [railsbridge/bridge_troll#394]
Currently, there's a little "i" in a circle for more info for each student or volunteer, and it shows some RSVP and profile information.

For students, add the description of the class level they selected.

**Comment by StevenXL** [comment]
@lilliealbert Is this still an open issue? I do see the little `i` as you mentioned on the right-hand side, but do the colored circle on the left-hand side not provide the class-level selected for each student? I just want to clear up the request, as I'd like to work on it if it is open.

**Comment by lilliealbert** [comment]
It is definitely still open. The color coding does tell you which class level, if you happen to know which color maps to which level. I'd like the longer description to appear on the modal that the "i" triggers.

If you want to view the levels, you currently have to know to click on the circle i icon on the colored header, which is pretty subtle.

The details about each course are in course.rb: https://github.com/railsbridge/bridge_troll/blob/master/app/models/course.rb

**Comment by StevenXL** [comment]
@lilliealbert I've addressed this issue, at least from what I understood that you wanted, with [pull request #415](https://github.com/railsbridge/bridge_troll/pull/415). Feedback is appreciated.

I'll try to work on some other items marked Ready for Action. Thanks!

**Comment by StevenXL** [comment]
@lilliealbert I think this is ready to be closed.
