### ISSUE TITLE
Add option for different CoC

### ISSUE THREAD

**Issue by carlisia** [railsbridge/bridge_troll#397]
Currently, a Bridge Troll event only let's you choose the Bridge Foundry CoC. However, GoBridge uses the Go CoC.

One possible way to resolve this is to have a listing with both options, and selecting one would display the link to the corresponding CoC in the published event.

**Comment by lilliealbert** [comment]
@ultrasaurus, what do you think about this?

My preference would be that all Bridges use the Bridge Foundry CoC, but I realize that might not be possible. Can you explain why y'all are using the GoBridge CoC?

**Comment by carlisia** [comment]
Sure. The Go language team has developed a CoC for the Go community, and that is the one we will use. We will have an addendum for some GB specific things.

**Comment by ultrasaurus** [comment]
I've reviewed the [Go CoC](https://golang.org/conduct) which is very much in the same spirit of our CoC.  Additionally it has a bunch of Go specific language and it does seem like it would benefit new community members to introduce them to the community standards.  The one thing that Bridge Foundry has which Go doesn't is "Do not ask anyone out on a date."  -- We effectively define asking someone for a date as   "Unwelcome sexual advances."  

I would consider it close enough that it work.  The benefit of exposing students to Go community norms outweighs the nuanced difference in my mind.

**Comment by carlisia** [comment]
Do we have an agreement to go forth with implementing this change?

**Comment by carlisia** [comment]
If we move in this direction, how about something like this:

![image](https://cloud.githubusercontent.com/assets/16508/11614322/e630f64e-9bf3-11e5-81ee-2fdeeb13c388.png)

**Comment by carlisia** [comment]
Or how about the version below, which would be defaulted to the RailsBridge CoC:

![image](https://cloud.githubusercontent.com/assets/16508/11614488/abd2ce9a-9bf9-11e5-8cec-a956dc56427e.png)

**Comment by lilliealbert** [comment]
@carlisia I don't think this is the kind of implementation I'd like to see. I'd rather that event organizers choose a chapter to associate their event with, and that chapter choice automatically display the correct code of conduct.

**Comment by carlisia** [comment]
Absolutely. I realize those suggestions above are a patch (I should've mentioned it.) But could we use it until we redesign the system to be able to associate events with a Bridge (I suppose you mean Bridge and not chapter)? I have 2 events ready to be added to BT and it would be odd for the organizer to have to choose a CoC that is not what GoBridge uses.

**Comment by carlisia** [comment]
I think this issue has been address and could be closed?

**Comment by tjgrathwell** [comment]
True that!
