### ISSUE TITLE
RailsBridge branding might make it confusing for people

### ISSUE THREAD

**Issue by carlisia** [railsbridge/bridge_troll#399]
I created my first BT event (in draft) to and was a bit taken aback when I looked at my mailbox and there was an email from RailsBridge. When I looked I knew what it was (a message informing that I had signed up.)

A lot of people in the Go community don't know of RailsBridge. For them and even for other who do, this message could be overlooked/dismissed as not relevant, when in fact it contains important information.

Is there something we can do about it? Maybe use Bridge Troll branding instead of RailsBridge?

![image](https://cloud.githubusercontent.com/assets/16508/11326821/8f02ade8-9128-11e5-8f29-51923b7b07b6.png)

**Comment by lilliealbert** [comment]
Would it be okay if I closed this issue and you add this to the previous one, as a comment of a place where we need de-RailsBridge-ify the app?

**Comment by carlisia** [comment]
Of course @lilliealbert!
