### ISSUE TITLE
Make events in Draft mode easier to find

### ISSUE THREAD

**Issue by carlisia** [railsbridge/bridge_troll#405]
I have an event in draft mode and the only way to access it is via my public profile. 

I think new organizers who are not familiar with the entire system might have a hard time finding that.

Would it be worthwhile to display it in the main page but marked as `draft`, or else make it easier to find?

**Comment by lilliealbert** [comment]
Can you double check if you have a filter selected on the front page that would be filtering out the draft? It should be showing up like this:

![screen shot 2015-11-28 at 10 38 16 am](https://cloud.githubusercontent.com/assets/978428/11453352/37fabfd4-95bc-11e5-959c-530cf87797df.png)

**Comment by carlisia** [comment]
@lilliealbert it's not there but I just figured out that I had entered a whatever date for my draft, which was 11/22 and, since it was in the past, it caused the event not to show like yours is showing. Sorry still getting the hand of things :)
