### ISSUE TITLE
If there are no upcoming events, don't show filter

### ISSUE THREAD

**Issue by ultrasaurus** [railsbridge/bridge_troll#413]
on the home page:  https://www.bridgetroll.org/

I was confused at first when I didn't see a list of regions in the popup (when there were no upcoming events):

![image](https://cloud.githubusercontent.com/assets/41906/11676266/b23c0a92-9de5-11e5-9902-8a77119defc9.png)

Let's hide it if there are no upcoming events.

**Comment by lilliealbert** [comment]
This is probably the first time since filtering was added that there were no workshops listed on the home page. Normally the dropdown would list all the regions that had upcoming workshops.

It is possible that we shouldn't show the dropdown when there are no upcoming events?

**Comment by ultrasaurus** [comment]
oh, yes, that would make sense.  I'll update the subject
