### ISSUE TITLE
Add a Friendly Error When an Organizer Tries to Assign a Blank User

### ISSUE THREAD

**Issue by StevenXL** [railsbridge/bridge_troll#416]
On the organizers page `http://localhost:3000/events/2/organizers`, a current organizer can assign a new organizer. If the current organizer clicks on the "Assign" button, the form is submitted without a proper `user_id` in the `params` hash. This causes an exception to be raised. Instead, we should have a more user-friendly message when a form is submitted without a proper `user_id` in the params hash.

**Comment by tjgrathwell** [comment]
Fixed now for organizers and checkiner assignment too. The primary fix is to just disable 'Assign' until something has been selected in the dropdown.
