### ISSUE TITLE
Add organizer names for past events on chapter show page

### ISSUE THREAD

**Issue by aneyzberg** [railsbridge/bridge_troll#432]
Currently there is no way to see who the organizers for a specific event are without clicking into the event. When we are planning a workshop it would be really helpful to see a list of  who has organized workshops in the past and that way we can see who to potentially contact. This would also give us an idea of how many workshops a single person has organized so as not to overwhelm a single volunteer.

I was thinking potentially adding a column to this [table](https://www.bridgetroll.org/chapters/3) that lists the organizers for the event would be one way to do this.

**Comment by JayaDarby** [comment]
testing
