### ISSUE TITLE
Add ability for chapter leads to approve events for their chapter

### ISSUE THREAD

**Issue by aneyzberg** [railsbridge/bridge_troll#433]
Being able to see and approve events for the San Francisco chapter. I know this might be a larger task, but given that the San Francisco chapter (using this as an example) is responsible for making sure events happen, it would be great if we had control over publishing those events
as well as seeing what events are in preview mode (for our respective chapter).

**Comment by lilliealbert** [comment]
This was completed in 6f5ca88ccdf019d708a8e17f9e73e21bb2c053be — @aneyzberg, wanna try this out on staging and see if it works for you?

**Comment by lilliealbert** [comment]
If you don't have an account at https://bridgetroll-staging.herokuapp.com, sign up for one, let me know, and I'll make you an SF chapter lead on staging. Then you can make a new event and try approving it!

**Comment by aneyzberg** [comment]
@lilliealbert awesome!!! signing up now!

**Comment by aneyzberg** [comment]
@lilliealbert I have created a new event :) And I can see it pending which is awesome, however I don't see where I can approve it.

**Comment by tjgrathwell** [comment]
I think this is working??

**Comment by aneyzberg** [comment]
This is working :)
