### ISSUE TITLE
If error, Email Attendees function drops selected recipients

### ISSUE THREAD

**Issue by kmolo** [railsbridge/bridge_troll#436]
I was using the Email Attendees function built into Bridgetroll, and, when I hit Send Email without having populated a Subject, I received an error message...and all the selected recipients of the email were removed + I had to re-add them.

I was really glad that the body of the message wasn't removed (whew).

**Comment by tjgrathwell** [comment]
It's fixed now, thanks for reporting!

**Comment by kmolo** [comment]
Wow, that was fast!  Awesome.  Thank you.  Loving bridge_troll as a tool + as an open source project.
