### ISSUE TITLE
Email organizers when event is approved

### ISSUE THREAD

**Issue by lilliealbert** [railsbridge/bridge_troll#440]
Since organizers can choose to send the announcement email when they want, we should email them when their event is approved!

Email should go to all organizers of the event and congratulate them for the excitement that is running an event.

**Comment by sidhene** [comment]
I've gotten the method, mailer, and 3/4 of the tests written but I'm blocked by a weird bug:

in app/controllers/events/unpublished_events_controller.rb line #27  causes:

```
Events::UnpublishedEventsController POST #publish if the announcement emails should be sent manually sends no announcement emails
     Failure/Error: <p>Dear <%= @event.organizers.first.first_name %>,</p>
     
     ActionView::Template::Error:
       undefined method `first_name' for nil:NilClass
```
While it's predictable that this test will fail (it hasn't been updated to not just count the number of emails sent), I can't figure out why I'm getting a nil:NilClass error when a similar command on line#24 works just fine.

details: https://docs.google.com/document/d/1E79tY1ia_irElc8w1JVPVwyVwD9UejiHe3lWyp1hq8A/edit

code: 
https://github.com/sidhene/bridge_troll/tree/approved_email_440

**Comment by sidhene** [comment]
Any news? I'm blocked here.

**Comment by lilliealbert** [comment]
I don't have time right now, but hopefully someone else does! https://twitter.com/lilliealbert/status/709781004374806528

**Comment by denniscollective** [comment]
*DISCLAIMER* I didn't run the tests, everything I'm saying is based on readi

It looks like in the controller, it switches the email that is sent whether email_on_approval is true of false. 

The new_event template which is sent in the passing cases is super simple, whereas the event_has_been_approved requires that the event has an organizer, and apparently, the event that is created in the test doesn't have an organizer.

I'm not that familiar with the bridge troll data model, so I don't know if an event should ever be able to not have an organizer, it seems the simplest fix to get this test to pass is to make the event have an organizer.

If events should always have organizers, this is indicative of a larger problem, and the factories should be updated to include this, and there should be a validation in the event model, but both of these things have the potential to cause issues in other places.

Sorry if what I'm saying is wrong/irrelevant, I'm not really familiar with this code, but that's what I noticed in my 15 minutes of poking around.

**Comment by sidhene** [comment]
Thanks Dennis. A missing organizer sounds consistent with the errors I am
seeing and that's something I should be able to fix. I'll take a look at
that and get back to you.


On Tue, Mar 15, 2016 at 2:50 PM, Dennis Collective <notifications@github.com

**Comment by sidhene** [comment]
@denniscollective - you were right. I assigned an organizer to the test event and now it fails the way I expected it to. Yay!

**Comment by sidhene** [comment]
And that got me unstuck. Test are in place and passing. Pull request submitted.

**Comment by denniscollective** [comment]
Awesome!
