### ISSUE TITLE
Users should get an email when they are added to an event as Organizers

### ISSUE THREAD

**Issue by tjgrathwell** [railsbridge/bridge_troll#444]
When an organizer adds another user to an event as an organizer, it should send that user a confirmation.

Suggested text:

> Subject: "You've been added as an organizer to #{@event.title}"
> 
> Body:
> Hey <%= @user.full_name %>,
> 
> You've been added as an organizer to.
> 
> If you think you shouldn't be an organizer, <% link_to 'you can remove yourself on the Organizers page', event_organizers_url(@event) %>

**Comment by sidhene** [comment]
I can probably do this since I just worked on mailers. I will announce when I start.

**Comment by sidhene** [comment]
Starting story

**Comment by sidhene** [comment]
Mostly done. I have a test that it happened, but it's just a 'counting emails' test and I want to make sure the email went to the new organizer.

In other tests, I see lines like 
`expect(recipients).to match_array(@event.organizers.map(&:email))`

What's the call for a single person, given that I have a User object for that person?

I'm not really blocked, but I'm tired and this seemed like the kind of question a random vol would know.

**Comment by tjgrathwell** [comment]
If you have a single user you're checking against, `expect(recipients).to match_array([@user.email])` could work

**Comment by sidhene** [comment]
Done. Pushed.

**Comment by tjgrathwell** [comment]
Pushed an amended version as fc9954251c57a38d9c5ca7d2f57cd8704030dff6
