### ISSUE TITLE
Add instructions for how to use Atom & RSS calendar feeds

### ISSUE THREAD

**Issue by lilliealbert** [railsbridge/bridge_troll#447]
Right now there are links to Atom & RSS feeds. I have no idea how they work, or how I'd get them into my calendar.

This requires a bit of research! And then probably adding a separate page with instructions, so we didn't have to clutter up the home page.

**Comment by jdjulian** [comment]
![image](https://cloud.githubusercontent.com/assets/12490142/13592294/a666b706-e4a5-11e5-99c8-e495c522cb43.png)

Me and @holyoke are working on this issue and this is what we have so far. @lilliealbert Do you intend to make a new url like "www.bridgetroll.org/feed_instructions"? Right now it links to an article that has instructions on how to use RSS feeds.

Alternatively we can also consider adding a modal or tooltip box. Let us know what do you think!

**Comment by lilliealbert** [comment]
This feature didn't quite work out, and no one seems clear on how RSS becomes a calendar feed, so I'm going to close this and instead we'll remove the feature. If someone someday wants to figure out how to make a region-specific calendar feed, please open a PR 👯
