### ISSUE TITLE
Make a new security list and change some other text

### ISSUE THREAD

**Issue by lilliealbert** [railsbridge/bridge_troll#449]
Let's remove this button: 

![screen shot 2016-02-28 at 8 05 38 pm](https://cloud.githubusercontent.com/assets/978428/13385575/6026424c-de57-11e5-9a7a-55560edcad49.png)

And add a new CSV that only returns people's names, sorted alphabetically by last name, to this page:

![screen shot 2016-02-28 at 8 07 07 pm](https://cloud.githubusercontent.com/assets/978428/13385531/e15ba5f6-de56-11e5-8648-fcf704ed4d7c.png)

And rename the buttons and add some helper text: 

* Add a new button: Download all names for building security
  * Helper text: "Includes first and last names for all attendees"
* Download Attendee names CSV becomes **Download all attendee info**
  * Helper text: "Includes name, role, dietary info, childcare info, job details, gender, plus-one host, if they are waitlisted, and waitlist position for all RSVP'd attendees."
* Download Student Details becomes **Download basic student info**
  * Helper text: "Includes name, class level, operating system, occupation, and gender for all students"

I'm not entirely sure how the helper text should be styled — maybe instead of having a series of inline buttons, you could have the button stacked in a column with the helper text next to it. Or if it looks terrible, maybe skip the helper text for now?

**Comment by shastablasta** [comment]
When I address the general UX side of things for the organizer console I'll also be thinking about helper text styling so skipping that aspect could be fine so someone isn't doubling up on efforts.

**Comment by jcdaviesauthor** [comment]
@zspencer and I are starting on this.
