### ISSUE TITLE
After a workshop, Bridgetroll should create private Google groups for workshop attendees who have opted in

### ISSUE THREAD

**Issue by rachelmyers** [railsbridge/bridge_troll#453]
Here's an idea. We could let workshop attendees opt in to joining a private Google group of people who attended the same workshop. (Ideally they would opt in after the workshop after they've met the other folks in this group, so perhaps in the workshop survey.) We automate the creation of the group after the workshop, perhaps when organizers send out the survey.

The goal is to give folks an easy way to stay in touch after the workshop, and Google groups would remove a lot of the need for community management.

**Comment by lilliealbert** [comment]
That's interesting. What if we tried it out non-automated first, so we can see whether or not people opt-in, and whether or not the groups have any activity?

**Comment by kmolo** [comment]
Bridge Foundry has a Discourse forum:
http://discourse.bridgefoundry.org/categories

...and so far each *Bridge can set up its own category (categories).  

Would this serve the desired purpose?

**Comment by lilliealbert** [comment]
Yeah, let's definitely promote the Discourse forum more than making Google groups.
