### ISSUE TITLE
Need a new GoBridge San Diego chapter

### ISSUE THREAD

**Issue by carlisia** [railsbridge/bridge_troll#454]
I wanted to open a BT today but there is no GoBridge chapter for San Diego. May I please get that included so I can start promoting it?

Thanks!

**Comment by lilliealbert** [comment]
There's a button on https://www.bridgetroll.org/chapters for creating a new chapter! Have fun!

**Comment by tjgrathwell** [comment]
Hey @carlisia, I've added you as an Organization Leader for GoBridge on Bridge Troll so you should see the "New Chapter" button and can create whichever GoBridge chapters you might want.

Let me know if it still doesn't work!

**Comment by carlisia** [comment]
Hi @tjgrathwell I worked, thank you! However... oops, I named it `San Diego` but wanted to change it to `GoBridge San Diego`, but there is no way for me to edit it.

**Comment by lilliealbert** [comment]
Fixed!

Also, I was like "what about the one I made this morning?" and then I realized that I had made it on staging. :stuck_out_tongue_closed_eyes:

**Comment by carlisia** [comment]
:+1:  thank you!
