### ISSUE TITLE
Should anyone be able to create chapters?

### ISSUE THREAD

**Issue by lilliealbert** [railsbridge/bridge_troll#455]
Currently, only admins can. This means that new workshops in new places would need an admin to create their chapter, which doesn't seem great.

**Comment by tjgrathwell** [comment]
I've added an Organization Leader role (94be27b007b8dc7b155ad5a6e78d9855aec6d7b5) whereby anyone who is considered an Organization Leader for a bridge/org (MobileBridge, GoBridge...) can create chapters.

Is there anything else what should be done?

**Comment by carlisia** [comment]
I can open a new issue but it would be great if an organization leader could view/receive the results of surveys, as well as approve workshops.

**Comment by carlisia** [comment]
And also edit chapter names for their organization.

**Comment by tjgrathwell** [comment]
@carlisia organization leaders should be able to do all those things now. Try it out!

**Comment by carlisia** [comment]
@tjgrathwell omygosh, awwwwwwsome!!! Thank youuuuuu! :dancer:
