### ISSUE TITLE
Add approve button to event show page

### ISSUE THREAD

**Issue by lilliealbert** [railsbridge/bridge_troll#461]
It'd be good for chapter and org leads to be able to approve events from the event itself. The visibility of the button should follow the same permissions as who is allowed to approve events.

(See our permissions model here: https://github.com/railsbridge/bridge_troll/wiki/Permissions-Model)

**Comment by deejayres** [comment]
#470

**Comment by lilliealbert** [comment]
Wooo! Thanks for adding this feature, @deejayres!! 💯
