### ISSUE TITLE
Build 'childcare volunteer' into the default

### ISSUE THREAD

**Issue by sidhene** [railsbridge/bridge_troll#462]
At present, the way childcare works is that the parent has to request it and the organizer has to hire it. This places additional burden on both the parent and the organizer (who is usually childless and clueless). This is contrary to Sarah Allen's vision and I think discouraging mothers. Since we have an abundance of volunteers, perhaps we should reserve a slot or two for childcare volunteers. This builds childcare provision into the default and saves money (since childcare, especially in SF, is expensive). 

This could be as simple as providing an option of childcaring along with teaching or as complicated as a separate rsvp.

**Comment by sidhene** [comment]
Combined with the ability to shuffle the waitlist #456 and some helper text, this could be effected without too much tinkering.

**Comment by rachelmyers** [comment]
I'm all for minimizing barriers for parents to attend a workshop. I have two thoughts.

First, it's not legal everywhere for volunteers to provide childcare, and Bridge Troll needs to be a useful tool for all chapters. For a workshop in Scotland, the law required that anyone providing childcare had to be licensed by the state; it was actually illegal for volunteers to watch kids. I'd push for the tool to solve the common problems for all workshop organizers, which doesn't include how to provide childcare.

Second, there's already an option when someone signs up to specify that they're interested in providing childcare. If you wanted to add an icon to volunteers interested in providing childcare, that information already exists in the database, from the days that Bridge Troll was mainly used in San Francisco.

Here's a screenshot from my own profile where I didn't volunteer to provide childcare:

<img width="304" alt="screen shot 2016-04-11 at 10 18 56 am" src="https://cloud.githubusercontent.com/assets/209641/14435910/f75f9c56-ffce-11e5-9593-07291464fc31.png">

**Comment by lilliealbert** [comment]
I agree with Rachel that the legal issues with childcare mean we should keep the tool more general. Thanks for the suggestion, though! ✨
