### ISSUE TITLE
Missing assets/sprockets files?

### ISSUE THREAD

**Issue by siruguri** [railsbridge/bridge_troll#464]
I feel like I'm missing something obvious ... multiple assets are not available in the source. I first got a "can't find select2" error; which went away if I added the select2-rails gem. Then I get 

```
couldn't find file 'DataTables' with type 'application/javascript'
```

I checked out the latest commit (3fc28f0) to master, and rebased (ffwd) to it from where I was (which was at a commit point that was really old.)

**Comment by siruguri** [comment]
Dang it, rtfm, Sameer! 

```
bin/setup
```

Realized things have come a ways since I last worked on this :)

**Comment by tjgrathwell** [comment]
You're not the first to run into this problem; it may still be good to add some kind of pre-check on server start to ensure that the JS dependencies have been installed.

Unfortunately, I don't think there's any corresponding `bower check` (like `bundle check`) to easily see if bower is up to date without doing a full `bower install`, which is loud and slow.

In the latest versions of Rails there's `bin/setup` and now `bin/update`, but it's probably not something that every team uses so it's hard to know you need to do it!
