### ISSUE TITLE
Where do I go to add a chapter?

### ISSUE THREAD

**Issue by dotthespeck** [railsbridge/bridge_troll#476]
On the form to create a new event, it says to contact admin to add a chapter. Where is the button to do that? A link in that statement on the form would be ideal. Thanks!

**Comment by lilliealbert** [comment]
Hi @dotthespeck, that's a really good point! I think we'll update that language to say to open an issue here!

We just need to know the organization you're involved in (RailsBridge, MobileBridge, ClojureBridge, and GoBridge are the ones we have so far), and a name for the chapter. We suggest naming your chapter after the organization and city or region, i.e. "GoBridge Kansas City".

**Comment by dotthespeck** [comment]
Hi, let's go with RailsBridge Portland, ME if that is okay! We need to differentiate ourselves from some other place named Portland out west :)

**Comment by lilliealbert** [comment]
Hi @dotthespeck — so sorry for the slow response!! RailsBridge Portland, ME lives! https://www.bridgetroll.org/chapters/51

Have a wonderful workshop!!!!
