### ISSUE TITLE
Displaying Zip Code on Locations Index Page

### ISSUE THREAD

**Issue by louiedp3** [railsbridge/bridge_troll#478]
It looks like we have a test that expects `locations_path` to have `@my_location.zip`.
https://github.com/railsbridge/bridge_troll/blob/master/spec/features/locations_request_spec.rb#L16

The locations `index.html`, however, does not have any references to `location.zip`
https://github.com/railsbridge/bridge_troll/blob/master/app/views/shared/_locations_table.html.erb

Is there a desire to show the zip code? If not then we can remove this code.

**Comment by tjgrathwell** [comment]
Good find, thanks!
