### ISSUE TITLE
import historical data

### ISSUE THREAD

**Issue by crkoehnen** [railsbridge/bridge_troll#485]
We have hosted five bridges but have never used bridge_troll.  We would like to import our historical data for reporting purposes.

**Comment by tjgrathwell** [comment]
What data do you want to import exactly?

If you just have a list of events that happened using other sites for registration (eventbrite, meetup...) an admin can add them as "External Events" and they will show up on event lists like https://www.bridgetroll.org/chapters/1 alongside any Bridgetroll events you create in the future.

For an External Event we just need the event name, URL start/end days, city, venue location and organizer names.

If you want to import user data or something like that, it would be a lot more complicated :)

**Comment by ultrasaurus** [comment]
We did this import a few years ago!  Closing this issue.
