### ISSUE TITLE
Admin for region unable to see events that are currently waiting to be published

### ISSUE THREAD

**Issue by aneyzberg** [railsbridge/bridge_troll#487]
#### Problem
As an admin, 
I previously had the ability to publish events that pertained to the region where I was an admin. 
In this case it was San Francisco.

Currently there is an event that is unpublished in the San Francisco Region, 
And I am unable to see it and publish it as an admin.

##### Current Views

My unpublished events view

![image](https://cloud.githubusercontent.com/assets/5723109/18190779/097dbf00-707a-11e6-8538-de2d3a5f870f.png)

The event that is waiting to be published- 
[https://www.bridgetroll.org/events/314](https://www.bridgetroll.org/events/314)
![image](https://cloud.githubusercontent.com/assets/5723109/18190811/32a295ae-707a-11e6-9e36-69291d84d56b.png)

#### Solution
As an admin, I would like to have the ability to view and publish unpublished events that pertain to my region.

**Comment by lilliealbert** [comment]
I just approved the event since it needed to get published, hopefully that doesn't make debugging this too much worse.

**Comment by aneyzberg** [comment]
@lilliealbert Thank you! That sounds good.

**Comment by tjgrathwell** [comment]
The event wasn't publishable for RailsBridge San Francisco chapter leaders because its chapter was set to ElmBridge San Francisco

!!:beer: cheers :beer:!!

**Comment by aneyzberg** [comment]
@tjgrathwell thank you!
