### ISSUE TITLE
Add Tampa Chapter

### ISSUE THREAD

**Issue by twinn** [railsbridge/bridge_troll#491]
We're hosting a rails bridge next month and per the instructions on bridge troll, it looks like we need to create this issue for a new Tampa Chapter. 

https://github.com/railsbridge/organizing/issues/99

**Comment by twinn** [comment]
I don't see any other groups named like this, but we're interested in doing maybe an Elm or Clojure bridge next year. Could the Chapter be a generic "Bridge Tampa", if that doesn't make sense "RailsBridge Tampa" is totally fine too.

**Comment by lilliealbert** [comment]
Given the structure of the organizations (esp. with regards to budgets & boards), each of the Bridges (GoBridge, ClojureBridge, RailsBridge, etc.) is a separate entity, and every chapter belongs to a specific org. So a generic Bridge isn't something that could exist right now.

...and RailsBridge Tampa lives! https://www.bridgetroll.org/chapters/55

(There's nothing stopping a RailsBridge chapter from putting on an event with the ClojureBridge or GoBridge curriculum, so I think it generally makes sense to pick a home base Bridge and then go from there. I know RailsBridge Hawai'i has put on a mobile workshop, so there's definitely precedent to mix-and-match curriculums.)
