### ISSUE TITLE
RustBridge Pittsburgh October 2016

### ISSUE THREAD

**Issue by melancholyfleur** [railsbridge/bridge_troll#492]
Title: RustBridge Pittsburgh October 2016

Date: Oct 21 - 22, 2016

Location: Pittsburgh, PA

Description: This workshop is intended for intermediate female developers who want to be introduced to Rust.

Venue: Think Through Math, 116 Federal St, Pittsburgh, PA 15212

Organizers:

Marylou Lenhart (marylou.lenhart@gmail.com)
Github: melancholyfleur
Twitter: @maryloulenhart

Sponsors
* Think Through Math
* Integer32

**Comment by melancholyfleur** [comment]
We'll need to add a new chapter for this event, and also the curriculum will be totally new because Rust is pretty new :)

**Comment by lilliealbert** [comment]
@melancholyfleur Was your goal with this issue just to get the chapter added? All the details about the event and such are something you'll add to Bridge Troll itself when making your event. For adding a chapter, all we need with the chapter name, which I assume is "RustBridge Pittsburgh". (Just want to make sure you know that Bridge Troll issues aren't for organizing workshops, just for getting updates done to Bridge Troll itself.)

For the curriculum, you'll want to follow the pattern in this file: https://github.com/railsbridge/bridge_troll/blob/master/app/models/course.rb

It would be great if you could make a PR with an update to the file with the course levels for your workshop.

And just to double check, you've been in touch with @ultrasaurus about starting a new Bridge? There's some onboarding stuff that she likes to go over with new Bridges 👯

**Comment by melancholyfleur** [comment]
@lilliealbert Hi :) Yes, it was just to add the chapter, I think. I haven't been in touch with anyone yet, I'm just starting, and I wasn't sure what all I needed to do. ^_^

**Comment by melancholyfleur** [comment]
Status update: I contacted @ultrasaurus today via email.

**Comment by ultrasaurus** [comment]
@melancholyfleur sorry for the delay!  the process is pretty lightweight, we just want to make sure you are connected with everyone and have everything you need.  Just responded to your email.

@lilliealbert [RustBridge](https://github.com/rust-community) has been working on starting a bridge since May or June.  Thanks for checking.  I think we can make sure everyone is connected in parallel with Marylou drafting the content for the event.  I'll also see if I can find out if the Europe workshop happened and if we can add it to the archives :)

This is very exciting!

**Comment by skade** [comment]
Hi, although I only started the initiative for the RustBridge and it's now handled by different people: the RustBridge workshop at RustFest happened and feedback is being collected.

You can find infos, tutorials and discussions here: https://github.com/rust-community/rustbridge

@melancholyfleur would you mind if i added you to the rustbridge github team?

The RustBridge team takes part in the rust community team meetings every Wednesday. The annoucement is always posted here: https://github.com/rust-community/team/issues

There's also someone building a website, but she's currently busy with other things.

**Comment by melancholyfleur** [comment]
Cool! So excited about all the support, thanks everyone. Looks like we're one step closer: our PR to add the Rust course was merged! 🎉  I'm not sure what the next step is; it looks like it needs to be pushed to production. (Also I'm not sure if that PR included our RustBridge Pittsburgh chapter being added or if that's a separate thing)

**Comment by lilliealbert** [comment]
@melancholyfleur We still need to add RustBridge as an organization (which needs to be done via a console, so I can't do it from my work laptop), so @tjgrathwell or I can get that done this weekend so you can move the event from the ClojureBridge chapter to the new RustBridge chapter.

**Comment by lilliealbert** [comment]
@melancholyfleur Just catching up on the comments on the curriculum update PR — you don't need to put in a PR with a migration for adding the RustBridge chapter, we can just do that by hand.

**Comment by melancholyfleur** [comment]
@lilliealbert Thanks so much ^_^ I'm sure github will let me know when things are done so I can get the sign up page out there for people to sign up. Again, I appreciate all the help!

**Comment by lilliealbert** [comment]
@melancholyfleur Okay, RustBridge & the Pittsburgh chapter have been added, and the Rust curriculum has also been deployed! Once you have a chance to update the course & chapter, things should be ready to go 😄
