### ISSUE TITLE
Adding ElixirBridge SF Chapter to Bridge Troll.

### ISSUE THREAD

**Issue by aneyzberg** [railsbridge/bridge_troll#501]
I would like to add the ElixirBridge San Francisco chapter to bridge troll.  Please let me know if there is anything else I need to do other than open the issue. Thank you!

**Comment by lilliealbert** [comment]
here you go! https://www.bridgetroll.org/chapters/57

:tada:

**Comment by aneyzberg** [comment]
@lilliealbert thank you!
