### ISSUE TITLE
external events should appear as past events when you search

### ISSUE THREAD

**Issue by ultrasaurus** [railsbridge/bridge_troll#512]
I think it would be nice if external events appeared as past events.

I noticed this since I spotted two of the same event via export.csv
![image](https://cloud.githubusercontent.com/assets/41906/20696038/6d0a9ce4-b5a5-11e6-8b33-108a9e1f3dd7.png)

And can see one here: https://www.bridgetroll.org/
![image](https://cloud.githubusercontent.com/assets/41906/20696018/4345c29e-b5a5-11e6-854b-2efcf6f64639.png)

And another here:
https://www.bridgetroll.org/external_events
![image](https://cloud.githubusercontent.com/assets/41906/20696048/8d86628c-b5a5-11e6-8465-87739eb29d63.png)

**Comment by tjgrathwell** [comment]
External events do appear as past events.

![screen shot 2016-11-28 at 8 25 34 pm](https://cloud.githubusercontent.com/assets/1041691/20696616/e0211502-b5a8-11e6-855f-64d556f2e3e2.png)

![screen shot 2016-11-28 at 8 30 50 pm](https://cloud.githubusercontent.com/assets/1041691/20696690/94850ee0-b5a9-11e6-95e9-c898aea54279.png)

![screen shot 2016-11-28 at 8 25 28 pm](https://cloud.githubusercontent.com/assets/1041691/20696618/e48e623e-b5a8-11e6-8776-628179a1d31f.png)

I don't see the Pittsburgh External Event you screenshotted, did you delete it?
The three Pittsburg events in the 'past events' table are all Bridgetroll events.

If you've identified a specific discrepancy between the homepage vs the csv vs the external events page, we can work on fixing that, but filing an issue claiming that external events don't work at all is not helpful.

**Comment by ultrasaurus** [comment]
I did delete the Pittsburgh External Event.  I didn't realize it was a specific discrepancy.. I was trying to be thorough in illustrating the different views.  I mistakenly though that the external events were not designed to show up as past events and I thought I was requesting a change.

Looking at it again, I see that in the regular listing, the external events do show up.  In trying to reproduce the behavior that I saw in the original report, I believe that the external events don't seem to show up when you search.  Does that sound accurate?

**Comment by ultrasaurus** [comment]
steps to reproduce:
1. go to last page and notice Aloha on Rails workshop:
![image](https://cloud.githubusercontent.com/assets/41906/20870684/1ca82bd6-ba41-11e6-98a6-073773e40dae.png)
2. Type "Hawaii" in the search box:
![image](https://cloud.githubusercontent.com/assets/41906/20870689/35562976-ba41-11e6-8a87-924c4fa8d94d.png)

**Comment by ultrasaurus** [comment]
Eeek.  HI != Hawaii

Never mind
