### ISSUE TITLE
Add ScalaBridge chapters

### ISSUE THREAD

**Issue by robinske** [railsbridge/bridge_troll#521]
Hello, our first ScalaBridge workshop will be in San Francisco on February 11th. We're also planning events in Seattle (February 18th) and Chicago (April 19th)

Could we add the following chapters to the list?

* ScalaBridge San Francisco
* ScalaBridge Seattle
* ScalaBridge Chicago

Thank you!

**Comment by tjgrathwell** [comment]
Added!
