### ISSUE TITLE
Addition of ScalaBridge Berlin chapter

### ISSUE THREAD

**Issue by dwestheide** [railsbridge/bridge_troll#532]
Hey there,

we have started to organize our first ScalaBridge Berlin event and would like to use BridgeTroll for it. Could you please add a ScalaBridge Berlin chapter? Thanks a lot in advance.

**Comment by tjgrathwell** [comment]
Should be there now, have a great event!!

**Comment by dwestheide** [comment]
Thanks a lot! :)
