### ISSUE TITLE
Being added as a leader for ElixirBridge to approve related events

### ISSUE THREAD

**Issue by aneyzberg** [railsbridge/bridge_troll#533]
@tjgrathwell I started ElixrBridge a few months ago, and I just posted another event and I realized I do not have permission to publish it. Can I be added as a leader for ElixirBridge so that I can publish events?

Please let me know if there is anything I need to do. Thank you!

**Comment by tjgrathwell** [comment]
should be done now :sunglasses:

**Comment by aneyzberg** [comment]
thank you @tjgrathwell!
