### ISSUE TITLE
New footer

### ISSUE THREAD

**Issue by shastablasta** [railsbridge/bridge_troll#535]
Create new footer above the troll image.

The txt and links to include are:

- [x] [About Bridge Foundry](http://bridgefoundry.org/what-we-do.html)

- [x] Past events
(Please create new page and move all the Past events info there)

- [x] [Code of Conduct](http://bridgefoundry.org/code-of-conduct/)

- [x] [Source Code](https://github.com/railsbridge/bridge_troll)

- [x] [Report a Bug](https://github.com/railsbridge/bridge_troll/issues)

Remove 
- [x] Remove bug text from the header

@careful-with-that-axe is working on this. thx!

**Comment by domlet** [comment]
I took a crack at this because I was looking for something simple to tackle – hope that's okay. Submitting a PR now.

**Comment by careful-with-that-axe** [comment]
@domlet Hello! I hope you are wonderful and send hugs. I got your branch and fixed something that was causing a test failure and then added a past event seed and more testing so your code will be ready to go soon.

You can see what went down here https://github.com/railsbridge/bridge_troll/pull/655 and definitely ping me if you see anything concerning but seemed like all is great and looking forward to getting your work merged in.

**Comment by careful-with-that-axe** [comment]
Closed with https://github.com/railsbridge/bridge_troll/pull/655
