### ISSUE TITLE
AlexaBridge Pittsburgh & Alexa Skill Development course

### ISSUE THREAD

**Issue by wonderwoman13** [railsbridge/bridge_troll#540]
Hello! I'm the previous organizer of ClojureBridge and RailsBridge Pittsburgh. I'm working on a new event! 

Can you please do the following for me: 

- Add the AlexaBridge Pittsburgh chapter
- Add "Alexa Skill Development" for the "What course is being offered?" question. 

Thank you for everything you all do! 💟

**Comment by careful-with-that-axe** [comment]
Heya! I am going through the open issues and wrapping them up, will take care of this now providing I have the right credentials otherwise I will track down someone who can and it will be a little longer.

From the other people who do so much more than I have for Bridge Troll, you are so welcome! And thanks for the work you do building workshops! ❤️

**Comment by careful-with-that-axe** [comment]
So I will either need to get access myself or someone else will add these, but I have pinged some people who can help so it won't be too much longer.

**Comment by wonderwoman13** [comment]
@careful-with-that-axe first off, amazing Github handle. Secondly, thank you for helping me! 🙌

**Comment by careful-with-that-axe** [comment]
Always glad to help and thanks! I am very fond of it myself. 😺  Wonder Woman is great too. :)

**Comment by careful-with-that-axe** [comment]
@wonderwoman13 you should be good to go now! I have created a course for you and added an AlexaBridge organization and a AlexaBridge Pittsburgh chapter.

Course wise though it will be good to have more information now that I have seen the fields required.

This is an example from the Elixir course:

name: Elixir
title: Elixir and Phoenix	
Description: This is an ElixirBridge event. The focus will be on developing a web application using Elixir and Phoenix.

Could you share the same with me for AlexaBridge and I will update it?

And let me know if anything else is needed, always glad to help and thanks again for creating the workshop. :)

**Comment by wonderwoman13** [comment]
@careful-with-that-axe 

name: Alexa
title: Amazon Alexa
Description: This is an Alexabridge event. The focus will be on developing Alexa Skills to be utilized by Amazon Echoes. 

Thanks so much! 💃

**Comment by careful-with-that-axe** [comment]
Updated! You are totally welcome. 💛

**Comment by wonderwoman13** [comment]
Hello! I need to re-open this because I'm missing the class levels on the event that was published. 

https://www.bridgetroll.org/events/360

Can we please include these 2 levels? 

Beginner = no programming experience
Intermediate = comfortable with one programming language (preferably Node.js, Java, C# or .NET)

Thank you, @careful-with-that-axe!

**Comment by careful-with-that-axe** [comment]
Hi @wonderwoman13 I think it is all sorted, check it out and see if this works for you?

https://www.bridgetroll.org/events/360/rsvp_preview?role_id=1

Glad to be able to help and it is good to know for the future to get the levels in as well. :)

**Comment by wonderwoman13** [comment]
Perfect! <3

**Comment by wonderwoman13** [comment]
Thanks again!
