### ISSUE TITLE
Creating a ScalaBridge chapter in Copenhagen

### ISSUE THREAD

**Issue by noelwelsh** [railsbridge/bridge_troll#546]
Hi,

We're organising a ScalaBridge event in Copenhagen:

http://event.scaladays.org/scaladays-cph-2017#00-Introduction

We'd like to use BridgeTroll to organise it. Can you create a chapter for Copenhagen?

Thanks,
Noel

**Comment by careful-with-that-axe** [comment]
Hi Noel, thanks for organizing this event! I just added the ScalaBridge Copenhagen chapter.

Please let me know if you need anything else or have any questions, I am happy to help. :)

**Comment by noelwelsh** [comment]
Awesome! Thanks!
