### ISSUE TITLE
style-guide 

### ISSUE THREAD

**Issue by LauraKirby** [railsbridge/bridge_troll#547]
commit 174f1d3276f079a aims to make the style-guide available publicly on Bridge Troll. 

<img width="1194" alt="code change" src="https://cloud.githubusercontent.com/assets/7623147/26368515/b9c63454-3fa6-11e7-962e-b0809e1ed359.png">

Currently, this page is not available. 
<img width="789" alt="bridge-troll-style-guide" src="https://cloud.githubusercontent.com/assets/7623147/26368388/57aabdd0-3fa6-11e7-8069-61b3ce912f1a.png">

**Comment by tjgrathwell** [comment]
Guess I had forgotten to deploy after that commit, :rocket: [it's live now](https://bridgetroll.org/styleguide) :rocket:

**Comment by LauraKirby** [comment]
Thank you @tjgrathwell
