### ISSUE TITLE
Can you add a "ScalaBridge Switzerland" chapter?

### ISSUE THREAD

**Issue by heathermiller** [railsbridge/bridge_troll#551]
Since Switzerland is so small, we are a handful of organizers that help each other organize ScalaBridge events in different cities (each a short train ride apart), such as Basel, Zurich, and hopefully soon Bern and Lausanne. We all commute to each other's city and help out there.

**Comment by tjgrathwell** [comment]
Done 👍

**Comment by heathermiller** [comment]
Thank you!
