### ISSUE TITLE
Better support single day events

### ISSUE THREAD

**Issue by jademcgough** [railsbridge/bridge_troll#552]
Bridge Troll supports displaying 2 or 3 day events, but it looks a bit clunky when you only have a single day:
<img width="529" alt="screen shot 2017-06-25 at 10 03 51 am" src="https://user-images.githubusercontent.com/1147449/27518155-b9c89446-598d-11e7-8c3a-7cd3b282efca.png">

@arceanea and I are going to look into this.

**Comment by tjgrathwell** [comment]
Was this event originally created with two sessions but then the organizers reconsidered?

There's no reason it needs to look like that, a single-session event is perfectly valid, see https://www.bridgetroll.org/events/351

The code currently doesn't allow sessions to be removed from existing events in the web UI if anyone has already RSVP'd. But I can clean it up in the console if that's how y'all want the event to be.

**Comment by jademcgough** [comment]
Ah, that'd make sense - just looked odd to me and I hadn't dug into the code yet. I'll close this out then.

**Comment by tjgrathwell** [comment]
Cool, I collapsed the sessions on that event so now it just looks like this: 

![screen shot 2017-06-25 at 12 34 05 pm](https://user-images.githubusercontent.com/1041691/27519147-aa87528c-59a2-11e7-8acb-ba2634415e2e.png)
