### ISSUE TITLE
Upcoming events filter doesn't include many regions

### ISSUE THREAD

**Issue by slhaines** [railsbridge/bridge_troll#553]
The Upcoming events filter doesn't let me select San Francisco Bay Area (or many other regions).

**Comment by tjgrathwell** [comment]
It only includes options in the filter for regions that have upcoming events, right now it doesn't seem SF has any.

We could have the dropdown include all the regions that have ever existed, but it would be very long and most of them would be empty. I'm open to suggestions about ways we could design this widget better!
