### ISSUE TITLE
Add ElixirBridge NYC chapter to BridgeTroll / ElixirBridge Seattle

### ISSUE THREAD

**Issue by aneyzberg** [railsbridge/bridge_troll#557]
I would like to add the ElixirBridge New York City & ElixirBridge Seattle chapter to Bridge Troll. Please let me know if there is anything else I need to do other than open the issue. Thank you!

**Comment by tjgrathwell** [comment]
Added 👍

**Comment by aneyzberg** [comment]
thank you @tjgrathwell!!!
