### ISSUE TITLE
Permissions to publish events for all ElixirBridge chapters

### ISSUE THREAD

**Issue by aneyzberg** [railsbridge/bridge_troll#558]
Hey @tjgrathwell, would it be possible for me to get permissions to publish events for all ElixirBridge Chapters. I just posted an event for ElixirBridge in NYC, but can't publish it. 

Let me know if you need anything else from me.

Thank you!!!

**Comment by tjgrathwell** [comment]
I've added you as an organization leader for ElixirBridge so things should work out now 👍

**Comment by aneyzberg** [comment]
@tjgrathwell Thank you!!!
