### ISSUE TITLE
ClojureBridge San Francisco

### ISSUE THREAD

**Issue by hannahhenderson** [railsbridge/bridge_troll#559]
Hello!

I don't know that there's actually a chapter in SF, but I'd love to post information on an upcoming ClojureBridge event in SF.

Eventbrite invite: http://www.clojurebridge.org/events/2017-09-15-san-francisco
Volunteer Sign up: https://www.volunteersignup.org/PWMYB (would love to use Bridge Troll in future!)

Official Clojure event: https://clojure.org/events/2017/clojurebridge-sanfrancisco
Official ClojureBridge event: http://www.clojurebridge.org/events/2017-09-15-san-francisco

@annguy3n is also an organizer for this upcoming event. We plan to hold ~quarterly ClojureBridge events going forward if we can make it work :)

**Comment by tjgrathwell** [comment]
Sorry for the delay in responding!

I've created it as an External Event in bridge troll which mainly just means it will show up at the bottom of http://railsbridge.org/. Additional feature work could make it show up as an upcoming event on bridgetroll.org, maybe someday?

I'm interested in hearing about what enhancements you might want to bridgetroll.org for using it in future workshops, if you've got any ideas there.

**Comment by hannahhenderson** [comment]
@tjgrathwell Thanks for making the event! Mostly BridgeTroll looks great to me, but there's no way (or suggested approach) to submit an event without being part of a chapter.
