### ISSUE TITLE
Adding a Test-Driven Development or Javascript/React Chapter & course for NYC

### ISSUE THREAD

**Issue by kwokster10** [railsbridge/bridge_troll#564]
Hi,

I would like to organize a Bridge workshop on Test-Driven Development with React here in NYC. My company, XO Group, has hosted RailsBridges before and has agreed to host again. However, there doesn't appear to be an appropriate chapter for the workshop I would like to hold. Could I please add a NYC TDD chapter? Along those lines, could the course also be added? I can provide information on the agenda and other details.

Thanks.

**Comment by rachelmyers** [comment]
Hi @kwokster10, if you're able to take a stab at this PR that might work better; adding a course  requires creating descriptions of the course and levels, and you probably have some of that in your head already. 

Here's a [sample PR adding a course](https://github.com/railsbridge/bridge_troll/pull/520/files) that can get you started. I know that file make it seem like it's not real data, but for the courses, the seeds populate the actual database. 😄  If you run into questions, I'm happy to help out, either here or via [email](rachelmariemyers@gmail.com)

**Comment by kwokster10** [comment]
@rachelmyers That's awesome! I'll work on that tonight. Thank you for the response. I was also wondering how mentors get assigned (as noted in the cookbook) since this will be my first time organizing a bridge workshop.

**Comment by rachelmyers** [comment]
Rad! I'll check out the PR tonight. I tried what I thought was the right way to create a chapter and it didn't work, so I'll figure that out tonight, too.

Mentors can add their preferences for what level they want to work with in their Bridge Troll profile, and for each workshop, Bridge Troll assigns mentors a group, and then the organizer can drag and drop the mentors to different groups.

**Comment by kwokster10** [comment]
Hi, @rachelmyers! I wanted to check in on the status of the chapter. Any luck figuring out how to create it?

**Comment by rachelmyers** [comment]
I didn't!  @tjgrathwell, what's the right way to create a chapter?

**Comment by tjgrathwell** [comment]
Sorry for the delay, I've created a "ReactBridge NYC" chapter and the "TDD With React" course should be available for selection.

I chose to go with "ReactBridge" rather than "JavascriptBridge" or "TDDBridge" because I felt like it matched better with the other *Bridge names, but maybe it should be called something different? We can revisit at any time, but you should be unblocked to create the event for now.
