### ISSUE TITLE
Add ElixirBridge Providence Rhode Island Chapter

### ISSUE THREAD

**Issue by aneyzberg** [railsbridge/bridge_troll#566]
I would like to add the ElixirBridge Providence chapter to Bridge Troll. Please let me know if there is anything else I need to do other than open the issue. Thank you!

**Comment by aneyzberg** [comment]
@tjgrathwell @ultrasaurus I am sorry to bug y'all - but we are adding an ElixirBridge workshop to the Elixir With Love conference in Providence Rhode Island in a couple weeks. I need to post asap so people have a chance to sign up. 

I'm not sure I have permissions to make these kinds of changes. Could one of you help me? Also if this is something I can do, I am happy to do so.

**Comment by tjgrathwell** [comment]
@aneyzberg You should be able to add a new chapter by going to '[homepage] -> Chapters -> New Chapter' when logged in as an admin.

For now, I've created the ElixirBridge Providence chapter so this should be good to go :rocket:
