### ISSUE TITLE
Cancel live event

### ISSUE THREAD

**Issue by mechamanny** [railsbridge/bridge_troll#569]
Hello @tjgrathwell, due to scheduling conflicts with the local railsbridge chapter, I need to cancel this event: 

https://www.bridgetroll.org/events/369

Is there a way for me to do so on the organizer console? I already notified all participants and volunteers through email.

**Comment by tjgrathwell** [comment]
Unfortunately there's no way to remove an event through the UI right now.
For now, I've kicked it back to Draft state, so it will stop showing on the homepage.
I could also delete it entirely if you feel that's necessary.

**Comment by mechamanny** [comment]
That works, thanks!
