### ISSUE TITLE
Remove ElixirBridge Providence 11/11/17 workshop from Site!

### ISSUE THREAD

**Issue by aneyzberg** [railsbridge/bridge_troll#570]
@tjgrathwell We need to remove the following workshop from the site -
 https://www.bridgetroll.org/events/373 - we are cancelling that is happening on  the workshop due to lack of signups. 

Is there anything I can do to help with this?

Thank you!
Anna

**Comment by tjgrathwell** [comment]
I'm a little late on the ball here but I've kicked the event back to Draft state so it won't show up anywhere.
Now that this has happened a few times I guess that should probably be made a feature in the app?
