### ISSUE TITLE
Cancel upcoming event?

### ISSUE THREAD

**Issue by sarahjschultz** [railsbridge/bridge_troll#571]
Hi there! 

I need to cancel an [upcoming event for the Denver Railsbridge chapter](https://www.bridgetroll.org/events/368) and can't seem to find a way to do this in the Organizer Console or after poking around in the code. We've emailed all of the students/TAs already but I'm nervous that someone might not see the email and will show up day-of to an empty room!

Do you have any recommendations for us as to how to proceed? Apologies if I am completely missing the functionality somewhere -- blame it on Thanksgiving brain fog!

Cheers!

**Comment by tjgrathwell** [comment]
I've kicked the event back into 'draft' state, so it won't show on the site anymore.

There's no feature on the site to do it, but this is the third time someone has needed to do this in as many months, so maybe it will exist soon.

**Comment by sarahjschultz** [comment]
Thanks so much @tjgrathwell !
