### ISSUE TITLE
Add 'RailsBridge Oakland' chapter to 'Organize an Event' drop-down menu

### ISSUE THREAD

**Issue by domlet** [railsbridge/bridge_troll#573]
On this page:
`https://www.bridgetroll.org/events/new`
Under:
`What Chapter is hosting? (required)`
Add:
`RailsBridge Oakland`

**Comment by careful-with-that-axe** [comment]
@domlet woot! Oakland chapter!!! You rock. I will add this a bit later today and then ping you when it is done. <3 Jane

**Comment by domlet** [comment]
You're the best – your energy is so contagious and I'm excited to work with
this community. :) Thank you!
ᐧ

**Comment by careful-with-that-axe** [comment]
Awww... thanks for kind words, I have been one drained kitten lately so now it is your energy I am getting contagion from! Like a relay race. ;)

Any interest in going a bit bigger? RailsBridge East Bay is open and needs some love. But totally understand if want to keep it city based, Oakland is a special/amazing place.

**Comment by domlet** [comment]
Oh! Of course – I currently live in Berkeley so East Bay is perfect –
thanks so much :)

Sending cosmic jam bands.
ᐧ

**Comment by careful-with-that-axe** [comment]
Yay! Please go ahead and roll with using East Bay chapter for your event.

This week and the next look a little hectic for me but after that I have loads of time and we will have to plot and plan East Bay coming back to life. The dream is SF and East Bay switch off workshops and support each other.

Also I will ping you directly to offer any other assistance. Thanks again for this, it brightened my week for sure. Cosmic jam bands back at ya.

**Comment by domlet** [comment]
Love – and will do. Thanks so much for your replies, and see you in
emailandia.
ᐧ
