### ISSUE TITLE
Add Admins to Bridgetroll - Isa, Ilen

### ISSUE THREAD

**Issue by iisa** [railsbridge/bridge_troll#585]
Hello,

We aren't able to access the admin features on Bridgetroll for Bridge Foundry work.

Isa user ID: 6
Ilen user ID: 11175

Would you be able to give us admin access?  Thanks in advance.  Isa

**Comment by tjgrathwell** [comment]
Looks like these users have the admin bit now, I didn't do it but I guess someone else did?

**Comment by ultrasaurus** [comment]
thanks for closing this @tjgrathwell 

FYI: this was taken care of by @careful-with-that-axe
