### ISSUE TITLE
Preload HSTS for bridgetroll.org

### ISSUE THREAD

**Issue by lgarron** [railsbridge/bridge_troll#587]
I think it would be nice to fully secure the site using HSTS. [Scott Helme's blog posts](https://scotthelme.co.uk/hsts-the-missing-link-in-tls/) outlines the benefits, and [hstspreload.org](https://hstspreload.org/?domain=bridgetroll.org) lists the requirements

I recommend the following steps:

1. Double-check that there are no subdomains that rely on HTTP.
2. Commit a trial header; test it on staging and prod for a few days (see #588).
```
Strict-Transport-Security: max-age=3600; includeSubDomains
```
3. Include a small request (e.g. a pixel) from each `https://www.bridgetroll.org` page to a resource on `https://bridgetroll.org`. (This is the least important part if your goal is full preloading, but it's a good idea.)
4. Change redirects from:
  - `http://bridgetroll.org` → `http://www.bridgetroll.org` → `https://www.bridgetroll.org`
  to:
  - `http://bridgetroll.org` → `https://bridgetroll.org` → `https://www.bridgetroll.org`
5. Bump the header for preloading (see #589):
```
Strict-Transport-Security: max-age=63072000; includeSubDomains; preload
```
6. Submit for HSTS preloading at https://hstspreload.org/?domain=bridgetroll.org

Unfortunately, it seems 4. is not controlled in the app. Is it a Heroku setting?

**Comment by michaelglass** [comment]
I'm not sure how hsts works with our `allow_insecure` routes. Thoughts?

**Comment by michaelglass** [comment]
The header doesn't affect anything badly, but I'm worried about forcing SSL on `allow_insecure` pages. What will happen without redirection if the browser thinks it should be ssl?

**Comment by siruguri** [comment]
I thought the role of `allow_insecure` is to not generate the redirect to SSL (443) for connections to 80 - that's how I read the code. Enabling HSTS means browsers will not in fact take advantage of this allowance in one of our routes, but that doesn't require us to remove the allowance for the headers to work. Did I not understand this correctly?

**Comment by michaelglass** [comment]
My question is: if browsers don't use http, will we break something?

**Comment by lgarron** [comment]
The site already supports HTTPS, so this shouldn't break any site that can already access that.

Sending anything but redirects over HTTP in 2019 is not great, although I understand it can be hard to address legacy integrations. One option is to serve redirect/HTTPS/preload HSTS for the important pages in modern clients, but not redirect some of the other paths.

**Comment by siruguri** [comment]
there's a staging server I can push a branch to, that we can check on... is it hsts_part_deux that I should push?

**Comment by michaelglass** [comment]
I'm also fine trying it out and fixing anything we accidentally break :p

**Comment by michaelglass** [comment]
done!
