### ISSUE TITLE
twitter authentication not working

### ISSUE THREAD

**Issue by ultrasaurus** [railsbridge/bridge_troll#591]
I just tried to log into bridgetroll.org and got an error when I tried to authenticate with twitter

redirected to: https://www.bridgetroll.org/users/auth/twitter?origin=%2F

![image](https://user-images.githubusercontent.com/41906/41502317-2d45d8ba-716c-11e8-966d-3b82b221cbcd.png)

**Comment by tjgrathwell** [comment]
Should be fixed now. Facebook login was also broken, should now also work.

I think both platforms had looser rules about callback URL matching; I had the callback set as "[domain]/users/auth/twitter" before, but they apparently require it to be "[domain]/users/auth/twitter/callback"

**Comment by ultrasaurus** [comment]
thank you!
