### ISSUE TITLE
Add ClojureBridge London chapter

### ISSUE THREAD

**Issue by jr0cket** [railsbridge/bridge_troll#609]
Please add ClojureBridge London as a chapter so I can add our latest event to BridgeTroll.

Unfortunately there seems no way to add an event without adding a chapter and the ClojureBridge London is not in the list.

Please let me know if you require any further information.

Our event details are at https://clojurebridgelondon.github.io/

Thank you for a great looking event site.  I hope we can use it for our events.

**Comment by ultrasaurus** [comment]
I just made a ClojureBridge London chapter.  I just noticed that we don't have any ClojureBridge admins right now -- it takes a little training to get up to speed on our less friendly (not as fully implemented) admin UI.  I'll reach out to the board, but if there's someone on the London leadership team who wants to learn how to be an admin, feel free to send an email to hello@bridgefoundry.org :)
