### ISSUE TITLE
upgrade testing gems

### ISSUE THREAD

**Issue by ultrasaurus** [railsbridge/bridge_troll#615]
With the upgrade to Ruby 2.5.3, I pinned the following gems to a specific version:
- [x] capybara
- [x] factory_bot
- [x] jasmine

Upgrading these to latest may involve some code changes (or maybe not, since we discovered other fixes needed since the initial ruby version update)

**Comment by michaelglass** [comment]
I added a dependabot integration that will automatically open PRs against new gem versions to help automate some of this work
