### ISSUE TITLE
Faker: DEPRECATION WARNING running tests

### ISSUE THREAD

**Issue by gkunwar** [railsbridge/bridge_troll#618]
While running test I got following deprecation warning from Faker gem.

> NOTE: Faker::Name.title is deprecated; use Faker::Job.title instead. It will be removed on or after 2018-09-01

**Comment by jhsu802701** [comment]
I addressed this in a Pull Request #621.

**Comment by gkunwar** [comment]
Since PR by @jhsu802701 has been merged. I have close this issue.
