### ISSUE TITLE
Add test coverage badge

### ISSUE THREAD

**Issue by jhsu802701** [railsbridge/bridge_troll#623]
I have added SimpleCov in Pull Request #606 .  We should add a code coverage badge.

(Good news: Test coverage is 93.35%.)

**Comment by ultrasaurus** [comment]
this is a great idea!

**Comment by jhsu802701** [comment]
My procedure for adding a code coverage badge is in my [Rails Neutrino site](https://www.railsneutrino.com/docs/chapter07).  I use Codecov because I found it easy to set up and use.  I used to use Code Climate for my code coverage badge, but it stopped working one day, and I couldn't figure out how to fix it.
