### ISSUE TITLE
Add ElmBridge Los Angeles chapter

### ISSUE THREAD

**Issue by emmacunningham** [railsbridge/bridge_troll#625]
Hello!  We're in the process of organizing our first ElmBridge event in Los Angeles, with the intent to have our first event in late March/early April.  Would appreciate getting the chapter added.  Thank you!

**Comment by emmacunningham** [comment]
Hi there, just wanted to ping again about this.  We have a date and venue locked in, so would love to get the chapter added so we can create the event and get the word out.  Thanks again!

**Comment by tjgrathwell** [comment]
Sorry for the delay! Here is the chapter: https://www.bridgetroll.org/chapters/121

**Comment by emmacunningham** [comment]
@tjgrathwell thank you so much!!  (and no need to apologize for the delay, appreciate the quick turnaround!!)
