### ISSUE TITLE
Address Github-reported vulnerabilities

### ISSUE THREAD

**Issue by siruguri** [railsbridge/bridge_troll#639]
Fixing actionview will require rails 5.2 which causes a lot of deprecations.

I am working on this now.

**Comment by btyy77c** [comment]
Are you referring to this issue?
https://weblog.rubyonrails.org/2019/3/13/Rails-4-2-5-1-5-1-6-2-have-been-released/

Rails released 5.0.7.2 for the security fix.  I think it's best to upgrade to 5.2 (or 6.0), but a quick fix would be to upgrade to 5.0.7.2

I already put in a similar pull request for a RailsBridge fix (https://github.com/railsbridge/railsbridge_dot_org/pulls)

**Comment by siruguri** [comment]
Thanks for pointing it out. I should have time to merge yours ahead of
getting to a full 5.2.2 merge.


Sameer (typed on a phone, please excuse typos.)

**Comment by siruguri** [comment]
@btyy77c  I couldn't quite merge your commits, because they are based on what looks like a very outdated commit history. I couldn't find an adequately recent parent commit to rebase on so I am essentially merging in your surgical update to Rails, plus the recommended update to Devise.
