### ISSUE TITLE
Unable to receive response from BridgeTroll Admins

### ISSUE THREAD

**Issue by btyy77c** [railsbridge/bridge_troll#644]
I submitted and event for approval on April 18th:
https://www.bridgetroll.org/events/472

I got an email stating I would hear back from an Admin in a few days.  I never heard back from the initial submission.  I also sent two different follow-up emails that I never received any response to. 

Does anyone have a contact I can reach out to, or another way to get an event approved?

Thanks!

**Comment by siruguri** [comment]
@btyy77c can you message me at cheapkettle at gmail, and I'll cc you with a couple of others who might have admin approval privileges?

**Comment by btyy77c** [comment]
Thanks!!!
