### ISSUE TITLE
Ruby Sass is deprecated

### ISSUE THREAD

**Issue by ultrasaurus** [railsbridge/bridge_troll#652]
`bundle install` yields this warning

```
Post-install message from sass:

Ruby Sass is deprecated and will be unmaintained as of 26 March 2019.

* If you use Sass as a command-line tool, we recommend using Dart Sass, the new
  primary implementation: https://sass-lang.com/install

* If you use Sass as a plug-in for a Ruby web framework, we recommend using the
  sassc gem: https://github.com/sass/sassc-ruby#readme

* For more details, please refer to the Sass blog:
  http://sass.logdown.com/posts/7081811
```

**Comment by careful-with-that-axe** [comment]
@ultrasaurus! So sorry! I had a branch I was working on but thought there might be something up with the seeds so I checked out master and then forgot and committed my fix right there. Possibly we can restrict merging directly to master? Totally my bad though I was super surprised when it went through - will be much more careful in future! 

Any rate, `sass-rails` is now upgraded to `sassc-rails` per the instructions and I didn't find any display issues/tests were green.
