### ISSUE TITLE
new contributor onboarding for @nerual

### ISSUE THREAD

**Issue by nerual** [railsbridge/bridge_troll#656]
Hello! I'm @nerual and I'd like to get started contributing to the Bridge Troll project. I had a chat with @rachelober and we discussed a few things, including how to best keep our efforts transparent and available to the wider community, and also how to get new people started with the most support possible. I'm going to drop a checklist below that I think gathers all the steps a newb could do to get going, as I come across them. We'll also use this as a way to provide buddy support for areas where I need help.

- [x] 👀Read [Contributing](https://github.com/railsbridge/bridge_troll/blob/master/CONTRIBUTING.md) guidelines
- [x] 🍴Clone the repo and get a local version working (expect more items nested here!)
- [x] Find a "Beginner Friendly" issue and work on it
- [x] 😰 File my first Pull Request (be sure to link it to this onboarding issue with markdown!)
- [x] 🎉 Celebrate my contribution to an awesome open source project!
- [x] (Specific to this issue:) turn the results of this Issue into an issue template for new contributors so we can help them help us!

**Comment by nerual** [comment]
First comment: dear @rachelober I can't assign myself, or you, or anyone to this issue. Please do the needful! 🙇‍♀ 

We might also want to consider making a 🏷(label) for these, so they're easy to filter in/out when people are looking at the issues in this repo.

**Comment by nerual** [comment]
When I ran `bin/setup` I got this error:
 ```
✘ nerual@jigglypuff  ~/bridge_troll   master  bin/setup
== Installing dependencies ==
https://github.com/thoughtbot/shoulda-matchers.git (at rails-5@4b160bd) is not yet checked out. Run `bundle install` first.
```

(I then obviously did that, I'm just recording this as things that went differently than the documentation says.)

**Comment by nerual** [comment]
This test fails after finishing `bin/setup` and running `bundle exec rake`
```
 nerual@jigglypuff  ~/bridge_troll   master  bundle exec rake
[...]
Finished in 1 minute 27.83 seconds (files took 5.58 seconds to load)
750 examples, 1 failure
Failed examples:

rspec ./spec/features/organizations/organizations_request_spec.rb:7 # organization pages organization index shows a map of events with their last event```

**Comment by nerual** [comment]
Soooo @rachelober there are no "Beginner Friendly" Issues, and I don't really see anything that sticks out as simple in the list... 😞

**Comment by rachelober** [comment]
Hey, @nerual thanks for all this! And ack about not having beginner-friendly tickets. As tomorrow is a holiday, I am going to take a look on Friday and see if I can suss out something that would be appropriate for you. If it's multi-step or maybe needs explaining for a Ruby newbie, maybe we can set up a time to pair program?

**Comment by ultrasaurus** [comment]
I think @rachelober said @nerual is an experienced coder who is new to Rails (or maybe just new to this app?)   If so, I think this one might be a good starter: https://github.com/railsbridge/bridge_troll/issues/624

**Comment by nerual** [comment]
I'm experienced with computer (more operational/sysadmin/network) things. I'd rate my programming skills at 3/10 on a good day, and I'm new to Ruby, Rails, and this app! That said, I'm happy to roll up my sleeves and poke at things. 🏋️‍♀️

**Comment by nerual** [comment]
Looks like I completed my checklist! I'm officially "onboarded"! 🎉
