### ISSUE TITLE
contributor on-boarding template

### ISSUE THREAD

**Issue by ultrasaurus** [railsbridge/bridge_troll#657]
love what @nerual did with a github issue for new contributor on-boarding https://github.com/railsbridge/bridge_troll/issues/656

it would be neat to have this as one of a few issue templates
- bug
- suggestion
- new contributor

**Comment by nerual** [comment]
i think it should be easy to crib the bug template from one of the million other repos that have one!

**Comment by nerual** [comment]
## Expected Behavior


## Current Behavior


## Possible Solution


## Steps to Reproduce


1.
2.
3.
4.

## Context (Environment)


```
<!--- Provide a general summary of the issue in the Title above -->

## Detailed Description
<!--- Provide a detailed description of the change or addition you are proposing -->

## Possible Implementation
<!--- Not obligatory, but suggest an idea for implementing addition or change -->
```

**Comment by nerual** [comment]
This is completed with PR #659
