### ISSUE TITLE
Please add Toronto as chapter

### ISSUE THREAD

**Issue by deniseyu** [railsbridge/bridge_troll#660]
Hi! We're looking to host GoBridge in September. We don't have an official Toronto chapter for any Bridges yet it looks like... so I guess we'll be the first to kick it off!

**Comment by rachelober** [comment]
Hi, @deniseyu! I have created GoBridge Toronto for you. You should be able to start selecting it and can see the main chapter page here https://www.bridgetroll.org/chapters/129

For Bridge Troll admins, I have added directions for how to create new chapters to the docs. https://github.com/railsbridge/bridge_troll/blob/master/doc/admin.md
