### ISSUE TITLE
Can you add a "ScalaBridge Pittsburgh" chapter?

### ISSUE THREAD

**Issue by heathermiller** [railsbridge/bridge_troll#663]
Hi,

I moved to Pittsburgh! I'd like to set up a ScalaBridge Pittsburgh chapter here. Can you create a ScalaBridge Pittsburgh chapter for us on Bridge Troll so we can be indexed?

Thank you!

Cheers,
Heather

**Comment by siruguri** [comment]
k, done. I just created it about fifteen minutes.

**Comment by siruguri** [comment]
![Screen Shot 2019-08-01 at 10 33 10 AM](https://user-images.githubusercontent.com/40653/62314415-c8706e80-b447-11e9-8d82-271ba94c2849.png)
