### ISSUE TITLE
Please add a ScalaBridge Amsterdam chapter

### ISSUE THREAD

**Issue by GerretS** [railsbridge/bridge_troll#664]
We are a new chapter organizing our first workshop.

It would be nice if this ticket could be processed quickly so we can put the invite live ASAP.

**Comment by siruguri** [comment]
I created one just now - sorry about the delay. I take it @GerretS the creator of #663 is part of your vols team?

**Comment by GerretS** [comment]
@siruguri no, I'm afraid I don't know her. ScalaBridge Amsterdam is organized by me and the creator of #665 .

**Comment by siruguri** [comment]
For reasons I cannot comprehend, my brain decided Amsterdam == Pittsburgh
:( I will now create 'ScalaBridge Amsterdam'

**Comment by siruguri** [comment]
k done now.
![Screen Shot 2019-07-31 at 9 51 26 PM](https://user-images.githubusercontent.com/40653/62314327-98c16680-b447-11e9-84e4-48c31d5b5fc5.png)
