### ISSUE TITLE
Add "Introduction Programming with Scala" as course being offered.

### ISSUE THREAD

**Issue by nmcb** [railsbridge/bridge_troll#665]
The introduction Scala curriculum for bridge events has been made to fit non-programmers as well as those that have already a bit of experience in some other programming language. To reflect this we would like to add the text "Introduction Programming with Scala" as one of the possible courses when organising an event as the current available Scala course "Scala for Programmers" might give attendees the impression that experience with programming is required.

**Comment by siruguri** [comment]
It appears that at least one past event organizer had an event that did require some programming experience, so (for the record) I will create a new course, rather than overwrite that one. 

To keep with a dominant existing naming pattern, would you be okay with "Learn to code with Scala"?

**Comment by nmcb** [comment]
Absolutely, "Learn to code with Scala" fits perfectly.

**Comment by siruguri** [comment]
sorry, I realized I needed a description. The one for the Scala for programmers course is 'This is a Scala programming event. Some programming knowledge expected, but you don't yet know Scala.'

The one for Ruby on Rails for example is, 'This is a Ruby on Rails event. The focus will be on developing web apps and programming in Ruby.  You can find all the curriculum materials at <a href=\"http://docs.railsbridge.org\">docs.railsbridge.org</a>'

I'm not sure if you will develop web apps with Scala, so could you suggest a description. How about:

'This is a Scala event. The focus will be on learning to code and (some programming concepts?) in Scala.  You can learn more at <a href=\"http://scalabridge.org\">scalabridge.org</a>'

Is that the right URL?

**Comment by nmcb** [comment]
Yup, that's the ScalaBridge site, we're in the process of setting it up.

How about "This is a Scala event. At the end of the day, you have learned to code and create a couple of fun applications in Scala yourself " ?

**Comment by siruguri** [comment]
Ok, done

**Comment by nmcb** [comment]
Thanks, Sameer, closed within an hour after I created the issue ... impressive.
