### ISSUE TITLE
Accidentally deleted myself as the organiser..

### ISSUE THREAD

**Issue by deniseyu** [railsbridge/bridge_troll#726]
Hi!

I'm trying to manually remove RSVPs from the BridgeTroll site because we're managing RSVPs off platform and it's confusing.

I accidentally removed myself and now can't access the organiser console anymore. In the short term, could someone restore me as the admin for the Toronto GoBridge event? (https://www.bridgetroll.org/events/483)

And in the longer term, it might be a good idea to remove the UI that enables you to remove yourself as the only admin from an event lol.

**Comment by siruguri** [comment]
![Screen Shot 2019-09-02 at 9 43 51 PM](https://user-images.githubusercontent.com/40653/64144742-ca24ad80-cdca-11e9-99db-2757b9c7a5aa.png)

@deniseyu  can you confirm you have what you need?

**Comment by deniseyu** [comment]
@siruguri thank you for the fast response! All good now 🙏
