### ISSUE TITLE
Need approval for ScalaBridge Silicon Valley event

### ISSUE THREAD

**Issue by adelbertc** [railsbridge/bridge_troll#757]
Hello,

We've created a BridgeTroll page for ScalaBridge Silicon Valley event that has been pending for a while now, wondering if anyone could take a look please?  cc @siruguri ?

Thanks!

**Comment by samdvr** [comment]
Link to this [event](https://www.bridgetroll.org/events/492).

**Comment by adelbertc** [comment]
Hah oops yes, I forgot to link to it!

**Comment by ultrasaurus** [comment]
Hi!  Sorry for the delay... I sent email with some feedback on the text.  (We need to expand admin/reviewer peoples.... will look into that separately)

**Comment by siruguri** [comment]
@ultrasaurus could you post a summary of the fdbk? I too looked at it today and couldn't immed approve because I was confused by the language, whether it was a 1 day or a 12 week event. Is that what you noted?
