### ISSUE TITLE
New chapter: RustBridge Berlin

### ISSUE THREAD

**Issue by fmoko** [railsbridge/bridge_troll#788]
Not sure what the process is here, but I run the RustBridge program and we've switched over to a chapter structure recently, with our first one being here in Berlin!

**Comment by siruguri** [comment]
Someone with production console access just needs to create a chapter
record associated to that organization. I should be able to get to it
tonight.

Sameer (typed on a phone, please excuse typos.)

**Comment by ultrasaurus** [comment]
actually, it can be done in the UI by a BridgeTroll admin (just a hidden URL) -- it's our list of things that need to be documented: https://github.com/railsbridge/bridge_troll/issues/633

I'll take care of that now

**Comment by ultrasaurus** [comment]
https://www.bridgetroll.org/chapters/134 -- created!

It would be great to establish one or more leaders for the RustBridge community in Berlin -- all that needs is a bit of on-boarding (both cuz our admin UI needs a bit of work and to talk about code-of-conduct and whatnot).    Now you can post events and folks from other regions/bridges can approve, so closing this issue as resolved.
