### ISSUE TITLE
Setup fails

### ISSUE THREAD

**Issue by ThatJohn** [railsbridge/bridge_troll#909]
Trying to get this to run, getting an error while running bin/setup:

```
rails aborted!
NameError: undefined local variable or method `__DIR__' for CoursePopulator:Module
Did you mean?  __id__
```
EDIT: Upor further investigation, it seems there's something wrong with the way the course_populator seed file reads the yaml file.

**Comment by ThatJohn** [comment]
Just fixed it by temporarily hardcodind the path to my YAML file in /db/seeds/course_populator.rb:
```
file = YAML.safe_load(File.expand_path('courses.yaml', '/home/john/Development/github/bridge_troll/db/seeds/'))
    YAML.load_file(file).each do |course|
```
Still have to find a way to generate dynamically, but I can't right now due to extreme time constrain.

**Comment by devraj-kumar** [comment]
The issue has been resolved now
