### ISSUE TITLE
Code issue

### ISSUE THREAD

**Issue by Digvijay091** [railsbridge/bridge_troll#937]
Hello everyone .... 
please explain this code:  for i in range(0, len(nums)-1):  in  use in below  
 def num_66(nums):
    for i in range(0, len(nums)-1):
            if nums[i:i+2] == [6,6]: 
            return True  
    
    return False

**Comment by playerpost32** [comment]
Not in range

**Comment by michaelglass** [comment]
this is off topic for this issue. Why did you think this was a good place to post?
