### ISSUE TITLE
PIP 

### ISSUE THREAD

**Issue by tayebassel-python** [railsbridge/bridge_troll#939]
i m  working with wing-personal7 ide with python 3.8 on Linux and  i have downloaded the mysql-connector package and other pip but when i import them on the code i get a problem it says that the module doesn t exist can u tell me what s the problem plz 
------------
>>>>>ModuleNotFoundError: No module named 'mysql.connector'; 'mysql' is not a package

**Comment by michaelglass** [comment]
I don't think this is related to bridge troll. We don't have any python stuff.
