### ISSUE TITLE
Looking to cancel upcoming event

### ISSUE THREAD

**Issue by mechamanny** [railsbridge/bridge_troll#989]
Hello! 

The Railsbridge Triangle organizers team would like to cancel the upcoming Railsbridge event, https://www.bridgetroll.org/events/505

We have emailed participants, I didn't see a way of doing this in the Organizer console, is it possible for someone to cancel this?

Thank you!

**Comment by michaelglass** [comment]
@mechamanny sorry about the late response. I see you figured out a workaround. This is something that doesn't exist yet but we should add.
